// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package goonfi

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "swap" instruction.
func NewSwapInstruction(
	// Params:
	isBidParam bool,

	// Accounts:
	userAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	userTokenAccountAAccount solanago.PublicKey,
	userTokenAccountBAccount solanago.PublicKey,
	poolTokenAccountAAccount solanago.PublicKey,
	poolTokenAccountBAccount solanago.PublicKey,
	mintAAccount solanago.PublicKey,
	mintBAccount solanago.PublicKey,
	account1Account solanago.PublicKey,
	account2Account solanago.PublicKey,
	sysvarInstructionsAccount solanago.PublicKey,
	tokenProgramAAccount solanago.PublicKey,
	tokenProgramBAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Swap[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `isBidParam`:
		err = enc__.Encode(isBidParam)
		if err != nil {
			return nil, errors.NewField("isBidParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "market": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, true, false))
		// Account 2 "user_token_account_a": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAAccount, true, false))
		// Account 3 "user_token_account_b": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountBAccount, true, false))
		// Account 4 "pool_token_account_a": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolTokenAccountAAccount, true, false))
		// Account 5 "pool_token_account_b": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolTokenAccountBAccount, true, false))
		// Account 6 "mint_a": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAAccount, false, false))
		// Account 7 "mint_b": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintBAccount, false, false))
		// Account 8 "account1": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(account1Account, false, false))
		// Account 9 "account2": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(account2Account, false, false))
		// Account 10 "sysvar_instructions": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sysvarInstructionsAccount, false, false))
		// Account 11 "token_program_a": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAAccount, false, false))
		// Account 12 "token_program_b": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramBAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
