// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package goonfi

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("goonuddtQRrWqqn5nFyczVKaie28f3kDkHWkHtURSLE")
