// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package dflow_gggregator_v4

// Account discriminators
var (
	Account_Order = [8]byte{134, 173, 223, 185, 77, 86, 28, 51}
)

// Event discriminators
var (
	Event_FeeEvent  = [8]byte{73, 79, 78, 127, 184, 213, 13, 220}
	Event_SwapEvent = [8]byte{64, 198, 205, 232, 38, 8, 113, 226}
)

// Instruction discriminators
var (
	Instruction_CloseEmptyTokenAccount               = [8]byte{232, 75, 140, 136, 250, 78, 224, 188}
	Instruction_CloseOrder                           = [8]byte{90, 103, 209, 28, 7, 63, 168, 4}
	Instruction_CreateReferralTokenAccountIdempotent = [8]byte{46, 232, 41, 144, 85, 37, 170, 175}
	Instruction_FillOrder                            = [8]byte{232, 122, 115, 25, 199, 143, 136, 162}
	Instruction_InitMarketLedgerIdempotent           = [8]byte{183, 43, 139, 79, 125, 225, 35, 159}
	Instruction_OpenOrder                            = [8]byte{206, 88, 88, 143, 38, 136, 50, 224}
	Instruction_Swap                                 = [8]byte{248, 198, 158, 145, 225, 117, 135, 200}
	Instruction_Swap2                                = [8]byte{65, 75, 63, 76, 235, 91, 91, 136}
	Instruction_Swap2WithDestination                 = [8]byte{95, 123, 213, 246, 122, 1, 86, 231}
	Instruction_Swap2WithDestinationNative           = [8]byte{222, 100, 184, 146, 186, 196, 105, 165}
	Instruction_SwapWithDestination                  = [8]byte{168, 172, 24, 77, 197, 156, 135, 101}
	Instruction_SwapWithDestinationNative            = [8]byte{205, 77, 127, 108, 241, 32, 196, 195}
	Instruction_TransferFee                          = [8]byte{129, 164, 196, 21, 177, 48, 180, 162}
	Instruction_TransferSol                          = [8]byte{78, 10, 236, 247, 109, 117, 21, 76}
	Instruction_TransferToSponsor                    = [8]byte{155, 179, 130, 151, 196, 139, 253, 163}
	Instruction_UnwrapSol                            = [8]byte{99, 40, 14, 105, 45, 107, 172, 201}
	Instruction_WrapSol                              = [8]byte{47, 62, 155, 172, 131, 205, 37, 201}
)
