// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package dflow_gggregator_v4

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "close_empty_token_account" instruction.
// Closes a token account if it has a zero balance
func NewCloseEmptyTokenAccountInstruction(
	tokenAccountAccount solanago.PublicKey,
	authorityAccount solanago.PublicKey,
	destinationAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_account": Writable, Non-signer, Required
		// The token account to close (supports both spl_token and spl_token_2022)
		accounts__.Append(solanago.NewAccountMeta(tokenAccountAccount, true, false))
		// Account 1 "authority": Read-only, Signer, Required
		// The authority of the token account. Must sign.
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, false, true))
		// Account 2 "destination": Writable, Non-signer, Required
		// The account to receive the rent from closing the token account.
		accounts__.Append(solanago.NewAccountMeta(destinationAccount, true, false))
		// Account 3 "token_program": Read-only, Non-signer, Required
		// The token program (either spl_token or spl_token_2022)
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "close_order" instruction.
// Closes an order, returning tokens from the order vault
func NewCloseOrderInstruction(
	orderAccount solanago.PublicKey,
	orderVaultAccount solanago.PublicKey,
	returnInputTokenAccountAccount solanago.PublicKey,
	returnRentToAccount solanago.PublicKey,
	closerAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "order": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderAccount, true, false))
		// Account 1 "order_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderVaultAccount, true, false))
		// Account 2 "return_input_token_account": Writable, Non-signer, Required
		// Account to which leftover tokens in the order vault should be returned.
		accounts__.Append(solanago.NewAccountMeta(returnInputTokenAccountAccount, true, false))
		// Account 3 "return_rent_to": Writable, Non-signer, Required
		// Account to which rent for the order account and vault should be returned.
		accounts__.Append(solanago.NewAccountMeta(returnRentToAccount, true, false))
		// Account 4 "closer": Read-only, Signer, Required
		// Account that is authorized to close the order
		accounts__.Append(solanago.NewAccountMeta(closerAccount, false, true))
		// Account 5 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 6 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create_referral_token_account_idempotent" instruction.
// Create a referral token account if it doesn't already exist
func NewCreateReferralTokenAccountIdempotentInstruction(
	payerAccount solanago.PublicKey,
	projectAccount solanago.PublicKey,
	referralAccountAccount solanago.PublicKey,
	referralTokenAccountAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	referralProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "project": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(projectAccount, false, false))
		// Account 2 "referral_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(referralAccountAccount, false, false))
		// Account 3 "referral_token_account": Writable, Non-signer, Required
		// The referral token account to create. This is a PDA of the Referral program whose seeds are
		// [b"referral_ata", referral_account, mint].
		accounts__.Append(solanago.NewAccountMeta(referralTokenAccountAccount, true, false))
		// Account 4 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 6 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 7 "referral_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(referralProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "fill_order" instruction.
// Fills an order, closing the order after filling it
func NewFillOrderInstruction(
	// Params:
	paramsParam FillOrderParams,

	// Accounts:
	orderAccount solanago.PublicKey,
	orderVaultAccount solanago.PublicKey,
	outputTokenAccountAccount solanago.PublicKey,
	returnInputTokenAccountAccount solanago.PublicKey,
	returnRentToAccount solanago.PublicKey,
	fillerInputTokenAccountAccount solanago.PublicKey,
	inputMintAccount solanago.PublicKey,
	fillerOutputTokenAccountAccount solanago.PublicKey,
	outputMintAccount solanago.PublicKey,
	fillerAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_FillOrder[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "order": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderAccount, true, false))
		// Account 1 "order_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderVaultAccount, true, false))
		// Account 2 "output_token_account": Writable, Non-signer, Required
		// Account to which output from the fill should be sent.
		accounts__.Append(solanago.NewAccountMeta(outputTokenAccountAccount, true, false))
		// Account 3 "return_input_token_account": Writable, Non-signer, Required
		// Account to which leftover tokens in the order vault should be returned.
		accounts__.Append(solanago.NewAccountMeta(returnInputTokenAccountAccount, true, false))
		// Account 4 "return_rent_to": Writable, Non-signer, Required
		// Account to which rent for the order account and vault should be returned.
		accounts__.Append(solanago.NewAccountMeta(returnRentToAccount, true, false))
		// Account 5 "filler_input_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(fillerInputTokenAccountAccount, true, false))
		// Account 6 "input_mint": Read-only, Non-signer, Optional
		// Input mint for the swap. Must be specified if the order inputs a mint for which the filler's
		// associated token account doesn't exist.
		accounts__.Append(solanago.NewAccountMeta(inputMintAccount, false, false))
		// Account 7 "filler_output_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(fillerOutputTokenAccountAccount, true, false))
		// Account 8 "output_mint": Read-only, Non-signer, Optional
		// Output mint for the swap. Must be specified if the order outputs native SOL or a mint for
		// which the filler's associated token account doesn't exist.
		accounts__.Append(solanago.NewAccountMeta(outputMintAccount, false, false))
		// Account 9 "filler": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(fillerAccount, true, true))
		// Account 10 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 11 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 12 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 13 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 14 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "init_market_ledger_idempotent" instruction.
// Initialize a market ledger if it doesn't already exist
func NewInitMarketLedgerIdempotentInstruction(
	// Params:
	marketIdParam [32]uint8,

	// Accounts:
	predictionsProgramAccount solanago.PublicKey,
	marketLedgerAccount solanago.PublicKey,
	marketLedgerRedemptionVaultAccount solanago.PublicKey,
	marketLedgerOrderVaultAccount solanago.PublicKey,
	marketLedgerReduceYesVaultAccount solanago.PublicKey,
	marketLedgerReduceNoVaultAccount solanago.PublicKey,
	settlementEscrowAccount solanago.PublicKey,
	escrowMintAccount solanago.PublicKey,
	marketYesOutcomeMintAccount solanago.PublicKey,
	marketNoOutcomeMintAccount solanago.PublicKey,
	payerAccount solanago.PublicKey,
	outcomeTokenProgramAccount solanago.PublicKey,
	escrowTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_InitMarketLedgerIdempotent[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `marketIdParam`:
		err = enc__.Encode(marketIdParam)
		if err != nil {
			return nil, errors.NewField("marketIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "predictions_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(predictionsProgramAccount, false, false))
		// Account 1 "market_ledger": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketLedgerAccount, false, false))
		// Account 2 "market_ledger_redemption_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketLedgerRedemptionVaultAccount, false, false))
		// Account 3 "market_ledger_order_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketLedgerOrderVaultAccount, false, false))
		// Account 4 "market_ledger_reduce_yes_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketLedgerReduceYesVaultAccount, false, false))
		// Account 5 "market_ledger_reduce_no_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketLedgerReduceNoVaultAccount, false, false))
		// Account 6 "settlement_escrow": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(settlementEscrowAccount, false, false))
		// Account 7 "escrow_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(escrowMintAccount, false, false))
		// Account 8 "market_yes_outcome_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketYesOutcomeMintAccount, false, false))
		// Account 9 "market_no_outcome_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketNoOutcomeMintAccount, false, false))
		// Account 10 "payer": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, false, false))
		// Account 11 "outcome_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(outcomeTokenProgramAccount, false, false))
		// Account 12 "escrow_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(escrowTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "open_order" instruction.
// Opens an order, escrowing the input tokens in the order vault
func NewOpenOrderInstruction(
	// Params:
	paramsParam OpenOrderParams,

	// Accounts:
	orderAccount solanago.PublicKey,
	orderVaultAccount solanago.PublicKey,
	inputTokenAccountAccount solanago.PublicKey,
	outputTokenAccountAccount solanago.PublicKey,
	returnInputTokenAccountAccount solanago.PublicKey,
	inputMintAccount solanago.PublicKey,
	userTokenAuthorityAccount solanago.PublicKey,
	feePayerAccount solanago.PublicKey,
	feeReceiverAccount solanago.PublicKey,
	rentDepositorAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_OpenOrder[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "order": Writable, Non-signer, Required
		// Order account that the instruction will create to store the order details
		accounts__.Append(solanago.NewAccountMeta(orderAccount, true, false))
		// Account 1 "order_vault": Writable, Non-signer, Required
		// Token account that the instruction will create to escrow the input tokens for the order
		accounts__.Append(solanago.NewAccountMeta(orderVaultAccount, true, false))
		// Account 2 "input_token_account": Writable, Non-signer, Required
		// Token account from which input tokens should be withdrawn to fund the order
		accounts__.Append(solanago.NewAccountMeta(inputTokenAccountAccount, true, false))
		// Account 3 "output_token_account": Read-only, Non-signer, Required
		// Account to which output from the fill should be sent. If the order specifies that it should
		// output native SOL, then this should be the user's wallet, although any account is allowed.
		// If the order doesn't specify that it should output native SOL, then this must be an SPL
		// token account, and the token account's mint determines the order's output mint.
		accounts__.Append(solanago.NewAccountMeta(outputTokenAccountAccount, false, false))
		// Account 4 "return_input_token_account": Read-only, Non-signer, Required
		// Account to which leftover tokens in the order vault should be returned when the order is
		// filled or closed. If the input is native SOL, this should be the user's wallet, although any
		// account is allowed. If the input is wrapped SOL or an SPL token, this must be an SPL token
		// account for the input mint.
		accounts__.Append(solanago.NewAccountMeta(returnInputTokenAccountAccount, false, false))
		// Account 5 "input_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(inputMintAccount, false, false))
		// Account 6 "user_token_authority": Read-only, Signer, Required
		// Authority of the input token account
		accounts__.Append(solanago.NewAccountMeta(userTokenAuthorityAccount, false, true))
		// Account 7 "fee_payer": Writable, Signer, Required
		// Account that pays the fee budget for the order
		accounts__.Append(solanago.NewAccountMeta(feePayerAccount, true, true))
		// Account 8 "fee_receiver": Writable, Non-signer, Required
		// Account that receives the fee budget funds
		accounts__.Append(solanago.NewAccountMeta(feeReceiverAccount, true, false))
		// Account 9 "rent_depositor": Writable, Signer, Required
		// Depositor for the order account and vault account rent
		accounts__.Append(solanago.NewAccountMeta(rentDepositorAccount, true, true))
		// Account 10 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 11 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 12 "rent": Read-only, Non-signer, Required, Address: SysvarRent111111111111111111111111111111111
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap" instruction.
// Executes a token swap
func NewSwapInstruction(
	// Params:
	paramsParam SwapParams,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	userTokenAuthorityAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Swap[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "user_token_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAuthorityAccount, false, true))
		// Account 4 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 5 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap2" instruction.
// Executes a token swap with a slippage fee
func NewSwap2Instruction(
	// Params:
	paramsParam Swap2Params,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	userTokenAuthorityAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Swap2[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "user_token_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAuthorityAccount, false, true))
		// Account 4 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 5 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap2_with_destination" instruction.
// Executes a token swap with a slippage fee. Outputs to the specified destination account.
func NewSwap2WithDestinationInstruction(
	// Params:
	paramsParam Swap2Params,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	userTokenAuthorityAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAuthorityAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Swap2WithDestination[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "user_token_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAuthorityAccount, false, true))
		// Account 4 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 5 "destination_token_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAuthorityAccount, false, false))
		// Account 6 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 7 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 8 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap2_with_destination_native" instruction.
// Executes a token swap with a slippage fee. Outputs native SOL to the specified destination // account by unwrapping WSOL.
func NewSwap2WithDestinationNativeInstruction(
	// Params:
	paramsParam Swap2Params,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	userTokenAuthorityAccount solanago.PublicKey,
	destinationAccountAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Swap2WithDestinationNative[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "user_token_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAuthorityAccount, false, true))
		// Account 4 "destination_account": Writable, Non-signer, Required
		// The destination account that will receive the native SOL
		accounts__.Append(solanago.NewAccountMeta(destinationAccountAccount, true, false))
		// Account 5 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 6 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_with_destination" instruction.
// Executes a token swap. Outputs to the specified destination account.
func NewSwapWithDestinationInstruction(
	// Params:
	paramsParam SwapParams,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	userTokenAuthorityAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAuthorityAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapWithDestination[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "user_token_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAuthorityAccount, false, true))
		// Account 4 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 5 "destination_token_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAuthorityAccount, false, false))
		// Account 6 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 7 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 8 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_with_destination_native" instruction.
// Executes a token swap. Outputs native SOL to the specified destination account by unwrapping // WSOL.
func NewSwapWithDestinationNativeInstruction(
	// Params:
	paramsParam SwapParams,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	userTokenAuthorityAccount solanago.PublicKey,
	destinationAccountAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapWithDestinationNative[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "user_token_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAuthorityAccount, false, true))
		// Account 4 "destination_account": Writable, Non-signer, Required
		// The destination account that will receive the native SOL
		accounts__.Append(solanago.NewAccountMeta(destinationAccountAccount, true, false))
		// Account 5 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 6 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "transfer_fee" instruction.
// Transfer an SPL token fee if the receiving account can receive it
func NewTransferFeeInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	fromAccount solanago.PublicKey,
	toAccount solanago.PublicKey,
	authorityAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_TransferFee[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "from": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(fromAccount, false, false))
		// Account 1 "to": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(toAccount, false, false))
		// Account 2 "authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, false, false))
		// Account 3 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 4 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 5 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "transfer_sol" instruction.
// Transfer native SOL from one account to another
func NewTransferSolInstruction(
	// Params:
	lamportsParam uint64,

	// Accounts:
	fromAccount solanago.PublicKey,
	toAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_TransferSol[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `lamportsParam`:
		err = enc__.Encode(lamportsParam)
		if err != nil {
			return nil, errors.NewField("lamportsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "from": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(fromAccount, false, false))
		// Account 1 "to": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(toAccount, false, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "transfer_to_sponsor" instruction.
// Transfer an SPL token to a sponsor's token account, creating the sponsor's token account if // necessary.
func NewTransferToSponsorInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	userTokenAuthorityAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	sponsorAccount solanago.PublicKey,
	sponsorTokenAccountAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_TransferToSponsor[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user_token_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAuthorityAccount, false, false))
		// Account 1 "user_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, false, false))
		// Account 2 "sponsor": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sponsorAccount, false, false))
		// Account 3 "sponsor_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sponsorTokenAccountAccount, false, false))
		// Account 4 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 5 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 6 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 7 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "unwrap_sol" instruction.
// Unwrap all SOL in the provided wrapped SOL token account
func NewUnwrapSolInstruction(
	ownerAccount solanago.PublicKey,
	wrappedSolAssociatedTokenAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "owner": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, false))
		// Account 1 "wrapped_sol_associated_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(wrappedSolAssociatedTokenAccountAccount, false, false))
		// Account 2 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "wrap_sol" instruction.
// Wrap SOL, creating a wrapped SOL associated token account if necessary
func NewWrapSolInstruction(
	// Params:
	lamportsParam uint64,

	// Accounts:
	fromAccount solanago.PublicKey,
	wrappedSolAssociatedTokenAccountAccount solanago.PublicKey,
	nativeMintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_WrapSol[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `lamportsParam`:
		err = enc__.Encode(lamportsParam)
		if err != nil {
			return nil, errors.NewField("lamportsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "from": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(fromAccount, false, false))
		// Account 1 "wrapped_sol_associated_token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(wrappedSolAssociatedTokenAccountAccount, false, false))
		// Account 2 "native_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(nativeMintAccount, false, false))
		// Account 3 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 4 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
