// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package manifest

// Account discriminators
var (
	Account_CreateMarketLog       = [8]byte{82, 29, 145, 232, 46, 155, 192, 85}
	Account_ClaimSeatLog          = [8]byte{214, 166, 73, 97, 12, 46, 214, 221}
	Account_DepositLog            = [8]byte{4, 113, 22, 194, 95, 153, 161, 82}
	Account_WithdrawLog           = [8]byte{173, 163, 236, 195, 206, 4, 120, 52}
	Account_FillLog               = [8]byte{117, 168, 16, 123, 102, 249, 153, 9}
	Account_PlaceOrderLog         = [8]byte{240, 60, 127, 232, 101, 68, 18, 118}
	Account_CancelOrderLog        = [8]byte{161, 219, 234, 66, 122, 48, 149, 48}
	Account_GlobalCreateLog       = [8]byte{99, 251, 73, 198, 59, 195, 129, 38}
	Account_GlobalAddTraderLog    = [8]byte{161, 62, 121, 35, 141, 28, 98, 87}
	Account_GlobalClaimSeatLog    = [8]byte{175, 209, 138, 35, 94, 11, 23, 151}
	Account_GlobalDepositLog      = [8]byte{123, 7, 220, 202, 167, 31, 159, 170}
	Account_GlobalWithdrawLog     = [8]byte{159, 196, 190, 92, 160, 124, 80, 199}
	Account_GlobalEvictLog        = [8]byte{23, 5, 167, 55, 98, 34, 79, 149}
	Account_GlobalCleanupLog      = [8]byte{148, 216, 2, 184, 252, 3, 155, 118}
	Account_QuoteAtoms            = [8]byte{235, 249, 36, 162, 34, 187, 97, 70}
	Account_BaseAtoms             = [8]byte{148, 199, 173, 74, 166, 32, 40, 73}
	Account_GlobalAtoms           = [8]byte{9, 216, 248, 118, 70, 214, 222, 234}
	Account_QuoteAtomsPerBaseAtom = [8]byte{116, 94, 46, 153, 86, 176, 78, 250}
)

// Event discriminators
var (
	Event_CreateMarketLog    = [8]byte{201, 115, 116, 164, 163, 128, 170, 99}
	Event_ClaimSeatLog       = [8]byte{97, 205, 223, 159, 56, 229, 87, 66}
	Event_DepositLog         = [8]byte{141, 186, 168, 252, 108, 141, 72, 94}
	Event_WithdrawLog        = [8]byte{235, 69, 115, 62, 185, 172, 126, 223}
	Event_FillLog            = [8]byte{150, 23, 41, 148, 152, 162, 215, 64}
	Event_PlaceOrderLog      = [8]byte{123, 167, 131, 93, 186, 96, 23, 75}
	Event_PlaceOrderLogV2    = [8]byte{193, 1, 152, 15, 203, 251, 169, 16}
	Event_CancelOrderLog     = [8]byte{154, 251, 151, 208, 31, 171, 15, 230}
	Event_GlobalCreateLog    = [8]byte{89, 110, 133, 172, 96, 236, 42, 208}
	Event_GlobalAddTraderLog = [8]byte{242, 251, 146, 254, 238, 183, 145, 138}
	Event_GlobalClaimSeatLog = [8]byte{137, 247, 186, 154, 124, 250, 46, 121}
	Event_GlobalDepositLog   = [8]byte{156, 175, 166, 69, 170, 93, 83, 155}
	Event_GlobalWithdrawLog  = [8]byte{83, 126, 78, 101, 162, 92, 253, 34}
	Event_GlobalEvictLog     = [8]byte{167, 121, 3, 30, 1, 219, 92, 104}
	Event_GlobalCleanupLog   = [8]byte{2, 129, 28, 80, 15, 153, 74, 235}
)

// Instruction discriminators
var (
	Instruction_CreateMarket    = [8]byte{103, 226, 97, 235, 200, 188, 251, 254}
	Instruction_ClaimSeat       = [8]byte{47, 217, 3, 139, 51, 238, 55, 107}
	Instruction_Deposit         = [8]byte{242, 35, 198, 137, 82, 225, 242, 182}
	Instruction_Withdraw        = [8]byte{183, 18, 70, 156, 148, 109, 161, 34}
	Instruction_Swap            = [8]byte{248, 198, 158, 145, 225, 117, 135, 200}
	Instruction_SwapV2          = [8]byte{43, 4, 237, 11, 26, 201, 30, 98}
	Instruction_Expand          = [8]byte{250, 208, 24, 3, 125, 211, 84, 69}
	Instruction_BatchUpdate     = [8]byte{57, 189, 226, 20, 239, 33, 98, 191}
	Instruction_GlobalCreate    = [8]byte{208, 199, 198, 107, 241, 172, 181, 156}
	Instruction_GlobalAddTrader = [8]byte{210, 68, 255, 2, 252, 16, 99, 222}
	Instruction_GlobalDeposit   = [8]byte{236, 252, 119, 50, 23, 95, 170, 108}
	Instruction_GlobalWithdraw  = [8]byte{131, 20, 103, 210, 221, 245, 52, 7}
	Instruction_GlobalEvict     = [8]byte{127, 132, 131, 253, 77, 207, 38, 188}
	Instruction_GlobalClean     = [8]byte{71, 227, 17, 42, 143, 96, 64, 22}
)
