// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package manifest

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms")
