// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package jupiter_aggregator

// Account discriminators
var (
	Account_TokenLedger = [8]byte{156, 247, 9, 188, 54, 108, 85, 77}
)

// Event discriminators
var (
	Event_FeeEvent                   = [8]byte{73, 79, 78, 127, 184, 213, 13, 220}
	Event_SwapEvent                  = [8]byte{64, 198, 205, 232, 38, 8, 113, 226}
	Event_SwapsEvent                 = [8]byte{152, 47, 78, 235, 192, 96, 110, 106}
	Event_CandidateSwapResults       = [8]byte{45, 9, 244, 30, 229, 52, 168, 123}
	Event_CandidateSwapQuoteError    = [8]byte{248, 134, 37, 55, 145, 177, 114, 79}
	Event_BestSwapOutAmountViolation = [8]byte{124, 66, 196, 51, 218, 173, 46, 93}
)

// Instruction discriminators
var (
	Instruction_Claim                              = [8]byte{62, 198, 214, 193, 213, 159, 108, 210}
	Instruction_ClaimToken                         = [8]byte{116, 206, 27, 191, 166, 19, 0, 73}
	Instruction_CloseToken                         = [8]byte{26, 74, 236, 151, 104, 64, 183, 249}
	Instruction_CreateTokenLedger                  = [8]byte{232, 242, 197, 253, 240, 143, 129, 52}
	Instruction_CreateTokenAccount                 = [8]byte{147, 241, 123, 100, 244, 132, 174, 118}
	Instruction_CloseWsolTokenAccount              = [8]byte{203, 129, 103, 133, 197, 125, 107, 86}
	Instruction_ExactOutRoute                      = [8]byte{208, 51, 239, 151, 123, 43, 237, 92}
	Instruction_Route                              = [8]byte{229, 23, 203, 151, 122, 227, 173, 42}
	Instruction_RouteWithTokenLedger               = [8]byte{150, 86, 71, 116, 167, 93, 14, 104}
	Instruction_SetTokenLedger                     = [8]byte{228, 85, 185, 112, 78, 79, 77, 2}
	Instruction_SharedAccountsExactOutRoute        = [8]byte{176, 209, 105, 168, 154, 125, 69, 62}
	Instruction_SharedAccountsRoute                = [8]byte{193, 32, 155, 51, 65, 214, 156, 129}
	Instruction_SharedAccountsRouteWithTokenLedger = [8]byte{230, 121, 143, 80, 119, 159, 106, 170}
	Instruction_ExactOutRouteV2                    = [8]byte{157, 138, 184, 82, 21, 244, 243, 36}
	Instruction_RouteV2                            = [8]byte{187, 100, 250, 204, 49, 196, 175, 20}
	Instruction_SharedAccountsExactOutRouteV2      = [8]byte{53, 96, 229, 202, 216, 187, 250, 24}
	Instruction_SharedAccountsRouteV2              = [8]byte{209, 152, 83, 147, 124, 254, 216, 233}
)
