// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package jupiter_aggregator

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_FeeEvent:
		value := new(FeeEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as FeeEvent: %w", err)
		}
		return value, nil
	case Event_SwapEvent:
		value := new(SwapEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SwapEvent: %w", err)
		}
		return value, nil
	case Event_SwapsEvent:
		value := new(SwapsEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SwapsEvent: %w", err)
		}
		return value, nil
	case Event_CandidateSwapResults:
		value := new(CandidateSwapResults)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CandidateSwapResults: %w", err)
		}
		return value, nil
	case Event_CandidateSwapQuoteError:
		value := new(CandidateSwapQuoteError)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CandidateSwapQuoteError: %w", err)
		}
		return value, nil
	case Event_BestSwapOutAmountViolation:
		value := new(BestSwapOutAmountViolation)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as BestSwapOutAmountViolation: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_FeeEvent(eventData []byte) (*FeeEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_FeeEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_FeeEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(FeeEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type FeeEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SwapEvent(eventData []byte) (*SwapEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SwapEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SwapEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SwapEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SwapEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SwapsEvent(eventData []byte) (*SwapsEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SwapsEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SwapsEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SwapsEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SwapsEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_CandidateSwapResults(eventData []byte) (*CandidateSwapResults, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CandidateSwapResults {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CandidateSwapResults, binary.FormatDiscriminator(discriminator))
	}
	event := new(CandidateSwapResults)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CandidateSwapResults: %w", err)
	}
	return event, nil
}

func ParseEvent_CandidateSwapQuoteError(eventData []byte) (*CandidateSwapQuoteError, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CandidateSwapQuoteError {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CandidateSwapQuoteError, binary.FormatDiscriminator(discriminator))
	}
	event := new(CandidateSwapQuoteError)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CandidateSwapQuoteError: %w", err)
	}
	return event, nil
}

func ParseEvent_BestSwapOutAmountViolation(eventData []byte) (*BestSwapOutAmountViolation, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_BestSwapOutAmountViolation {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_BestSwapOutAmountViolation, binary.FormatDiscriminator(discriminator))
	}
	event := new(BestSwapOutAmountViolation)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type BestSwapOutAmountViolation: %w", err)
	}
	return event, nil
}
