// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package jupiter_aggregator

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "claim" instruction.
func NewClaimInstruction(
	// Params:
	idParam uint8,

	// Accounts:
	walletAccount solanago.PublicKey,
	programAuthorityAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Claim[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `idParam`:
		err = enc__.Encode(idParam)
		if err != nil {
			return nil, errors.NewField("idParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "wallet": Writable, Non-signer, Required, Address: 7JQeyNK55fkUPUmEotupBFpiBGpgEQYLe8Ht1VdSfxcP
		accounts__.Append(solanago.NewAccountMeta(walletAccount, true, false))
		// Account 1 "program_authority": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAuthorityAccount, true, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "claim_token" instruction.
func NewClaimTokenInstruction(
	// Params:
	idParam uint8,

	// Accounts:
	payerAccount solanago.PublicKey,
	walletAccount solanago.PublicKey,
	programAuthorityAccount solanago.PublicKey,
	programTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ClaimToken[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `idParam`:
		err = enc__.Encode(idParam)
		if err != nil {
			return nil, errors.NewField("idParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "wallet": Read-only, Non-signer, Required, Address: 7JQeyNK55fkUPUmEotupBFpiBGpgEQYLe8Ht1VdSfxcP
		accounts__.Append(solanago.NewAccountMeta(walletAccount, false, false))
		// Account 2 "program_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAuthorityAccount, false, false))
		// Account 3 "program_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programTokenAccountAccount, true, false))
		// Account 4 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 5 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 6 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 7 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 8 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "close_token" instruction.
func NewCloseTokenInstruction(
	// Params:
	idParam uint8,
	burnAllParam bool,

	// Accounts:
	operatorAccount solanago.PublicKey,
	walletAccount solanago.PublicKey,
	programAuthorityAccount solanago.PublicKey,
	programTokenAccountAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CloseToken[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `idParam`:
		err = enc__.Encode(idParam)
		if err != nil {
			return nil, errors.NewField("idParam", err)
		}
		// Serialize `burnAllParam`:
		err = enc__.Encode(burnAllParam)
		if err != nil {
			return nil, errors.NewField("burnAllParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "operator": Read-only, Signer, Required, Address: 9RAufBfjGQjDfrwxeyKmZWPADHSb8HcoqCdrmpqvCr1g
		accounts__.Append(solanago.NewAccountMeta(operatorAccount, false, true))
		// Account 1 "wallet": Writable, Non-signer, Required, Address: 7JQeyNK55fkUPUmEotupBFpiBGpgEQYLe8Ht1VdSfxcP
		accounts__.Append(solanago.NewAccountMeta(walletAccount, true, false))
		// Account 2 "program_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAuthorityAccount, false, false))
		// Account 3 "program_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programTokenAccountAccount, true, false))
		// Account 4 "mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, true, false))
		// Account 5 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "create_token_ledger" instruction.
func NewCreateTokenLedgerInstruction(
	tokenLedgerAccount solanago.PublicKey,
	payerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_ledger": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenLedgerAccount, true, true))
		// Account 1 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create_token_account" instruction.
func NewCreateTokenAccountInstruction(
	// Params:
	bumpParam uint8,

	// Accounts:
	tokenAccountAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CreateTokenAccount[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `bumpParam`:
		err = enc__.Encode(bumpParam)
		if err != nil {
			return nil, errors.NewField("bumpParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenAccountAccount, true, false))
		// Account 1 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 2 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 3 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 4 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "close_wsol_token_account" instruction.
func NewCloseWsolTokenAccountInstruction(
	tokenAccountAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenAccountAccount, true, false))
		// Account 1 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 2 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "exact_out_route" instruction.
func NewExactOutRouteInstruction(
	// Params:
	routePlanParam []RoutePlanStep,
	outAmountParam uint64,
	quotedInAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint8,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	userTransferAuthorityAccount solanago.PublicKey,
	userSourceTokenAccountAccount solanago.PublicKey,
	userDestinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	token2022ProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ExactOutRoute[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
		// Serialize `outAmountParam`:
		err = enc__.Encode(outAmountParam)
		if err != nil {
			return nil, errors.NewField("outAmountParam", err)
		}
		// Serialize `quotedInAmountParam`:
		err = enc__.Encode(quotedInAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedInAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 2 "user_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userSourceTokenAccountAccount, true, false))
		// Account 3 "user_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userDestinationTokenAccountAccount, true, false))
		// Account 4 "destination_token_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 5 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 6 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 7 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 8 "token_2022_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(token2022ProgramAccount, false, false))
		// Account 9 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 10 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "route" instruction.
func NewRouteInstruction(
	// Params:
	routePlanParam []RoutePlanStep,
	inAmountParam uint64,
	quotedOutAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint8,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	userTransferAuthorityAccount solanago.PublicKey,
	userSourceTokenAccountAccount solanago.PublicKey,
	userDestinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Route[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
		// Serialize `inAmountParam`:
		err = enc__.Encode(inAmountParam)
		if err != nil {
			return nil, errors.NewField("inAmountParam", err)
		}
		// Serialize `quotedOutAmountParam`:
		err = enc__.Encode(quotedOutAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedOutAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 2 "user_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userSourceTokenAccountAccount, true, false))
		// Account 3 "user_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userDestinationTokenAccountAccount, true, false))
		// Account 4 "destination_token_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 5 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 6 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 7 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 8 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "route_with_token_ledger" instruction.
func NewRouteWithTokenLedgerInstruction(
	// Params:
	routePlanParam []RoutePlanStep,
	quotedOutAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint8,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	userTransferAuthorityAccount solanago.PublicKey,
	userSourceTokenAccountAccount solanago.PublicKey,
	userDestinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	tokenLedgerAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RouteWithTokenLedger[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
		// Serialize `quotedOutAmountParam`:
		err = enc__.Encode(quotedOutAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedOutAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 2 "user_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userSourceTokenAccountAccount, true, false))
		// Account 3 "user_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userDestinationTokenAccountAccount, true, false))
		// Account 4 "destination_token_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 5 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 6 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 7 "token_ledger": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenLedgerAccount, false, false))
		// Account 8 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 9 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_token_ledger" instruction.
func NewSetTokenLedgerInstruction(
	tokenLedgerAccount solanago.PublicKey,
	tokenAccountAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_ledger": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenLedgerAccount, true, false))
		// Account 1 "token_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenAccountAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "shared_accounts_exact_out_route" instruction.
func NewSharedAccountsExactOutRouteInstruction(
	// Params:
	idParam uint8,
	routePlanParam []RoutePlanStep,
	outAmountParam uint64,
	quotedInAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint8,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	programAuthorityAccount solanago.PublicKey,
	userTransferAuthorityAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	programSourceTokenAccountAccount solanago.PublicKey,
	programDestinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	token2022ProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SharedAccountsExactOutRoute[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `idParam`:
		err = enc__.Encode(idParam)
		if err != nil {
			return nil, errors.NewField("idParam", err)
		}
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
		// Serialize `outAmountParam`:
		err = enc__.Encode(outAmountParam)
		if err != nil {
			return nil, errors.NewField("outAmountParam", err)
		}
		// Serialize `quotedInAmountParam`:
		err = enc__.Encode(quotedInAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedInAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "program_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAuthorityAccount, false, false))
		// Account 2 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 3 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 4 "program_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programSourceTokenAccountAccount, true, false))
		// Account 5 "program_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programDestinationTokenAccountAccount, true, false))
		// Account 6 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 7 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 8 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 9 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 10 "token_2022_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(token2022ProgramAccount, false, false))
		// Account 11 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 12 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "shared_accounts_route" instruction.
func NewSharedAccountsRouteInstruction(
	// Params:
	idParam uint8,
	routePlanParam []RoutePlanStep,
	inAmountParam uint64,
	quotedOutAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint8,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	programAuthorityAccount solanago.PublicKey,
	userTransferAuthorityAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	programSourceTokenAccountAccount solanago.PublicKey,
	programDestinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	token2022ProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SharedAccountsRoute[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `idParam`:
		err = enc__.Encode(idParam)
		if err != nil {
			return nil, errors.NewField("idParam", err)
		}
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
		// Serialize `inAmountParam`:
		err = enc__.Encode(inAmountParam)
		if err != nil {
			return nil, errors.NewField("inAmountParam", err)
		}
		// Serialize `quotedOutAmountParam`:
		err = enc__.Encode(quotedOutAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedOutAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "program_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAuthorityAccount, false, false))
		// Account 2 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 3 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 4 "program_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programSourceTokenAccountAccount, true, false))
		// Account 5 "program_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programDestinationTokenAccountAccount, true, false))
		// Account 6 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 7 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 8 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 9 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 10 "token_2022_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(token2022ProgramAccount, false, false))
		// Account 11 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 12 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "shared_accounts_route_with_token_ledger" instruction.
func NewSharedAccountsRouteWithTokenLedgerInstruction(
	// Params:
	idParam uint8,
	routePlanParam []RoutePlanStep,
	quotedOutAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint8,

	// Accounts:
	tokenProgramAccount solanago.PublicKey,
	programAuthorityAccount solanago.PublicKey,
	userTransferAuthorityAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	programSourceTokenAccountAccount solanago.PublicKey,
	programDestinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	token2022ProgramAccount solanago.PublicKey,
	tokenLedgerAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SharedAccountsRouteWithTokenLedger[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `idParam`:
		err = enc__.Encode(idParam)
		if err != nil {
			return nil, errors.NewField("idParam", err)
		}
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
		// Serialize `quotedOutAmountParam`:
		err = enc__.Encode(quotedOutAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedOutAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 1 "program_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAuthorityAccount, false, false))
		// Account 2 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 3 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 4 "program_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programSourceTokenAccountAccount, true, false))
		// Account 5 "program_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programDestinationTokenAccountAccount, true, false))
		// Account 6 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 7 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 8 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 9 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 10 "token_2022_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(token2022ProgramAccount, false, false))
		// Account 11 "token_ledger": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenLedgerAccount, false, false))
		// Account 12 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 13 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "exact_out_route_v2" instruction.
func NewExactOutRouteV2Instruction(
	// Params:
	outAmountParam uint64,
	quotedInAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint16,
	positiveSlippageBpsParam uint16,
	routePlanParam []RoutePlanStepV2,

	// Accounts:
	userTransferAuthorityAccount solanago.PublicKey,
	userSourceTokenAccountAccount solanago.PublicKey,
	userDestinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ExactOutRouteV2[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `outAmountParam`:
		err = enc__.Encode(outAmountParam)
		if err != nil {
			return nil, errors.NewField("outAmountParam", err)
		}
		// Serialize `quotedInAmountParam`:
		err = enc__.Encode(quotedInAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedInAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
		// Serialize `positiveSlippageBpsParam`:
		err = enc__.Encode(positiveSlippageBpsParam)
		if err != nil {
			return nil, errors.NewField("positiveSlippageBpsParam", err)
		}
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 1 "user_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userSourceTokenAccountAccount, true, false))
		// Account 2 "user_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userDestinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "source_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 6 "destination_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 7 "destination_token_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 8 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 9 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "route_v2" instruction.
func NewRouteV2Instruction(
	// Params:
	inAmountParam uint64,
	quotedOutAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint16,
	positiveSlippageBpsParam uint16,
	routePlanParam []RoutePlanStepV2,

	// Accounts:
	userTransferAuthorityAccount solanago.PublicKey,
	userSourceTokenAccountAccount solanago.PublicKey,
	userDestinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RouteV2[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `inAmountParam`:
		err = enc__.Encode(inAmountParam)
		if err != nil {
			return nil, errors.NewField("inAmountParam", err)
		}
		// Serialize `quotedOutAmountParam`:
		err = enc__.Encode(quotedOutAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedOutAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
		// Serialize `positiveSlippageBpsParam`:
		err = enc__.Encode(positiveSlippageBpsParam)
		if err != nil {
			return nil, errors.NewField("positiveSlippageBpsParam", err)
		}
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 1 "user_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userSourceTokenAccountAccount, true, false))
		// Account 2 "user_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userDestinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "source_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 6 "destination_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 7 "destination_token_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 8 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 9 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "shared_accounts_exact_out_route_v2" instruction.
func NewSharedAccountsExactOutRouteV2Instruction(
	// Params:
	idParam uint8,
	outAmountParam uint64,
	quotedInAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint16,
	positiveSlippageBpsParam uint16,
	routePlanParam []RoutePlanStepV2,

	// Accounts:
	programAuthorityAccount solanago.PublicKey,
	userTransferAuthorityAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	programSourceTokenAccountAccount solanago.PublicKey,
	programDestinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SharedAccountsExactOutRouteV2[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `idParam`:
		err = enc__.Encode(idParam)
		if err != nil {
			return nil, errors.NewField("idParam", err)
		}
		// Serialize `outAmountParam`:
		err = enc__.Encode(outAmountParam)
		if err != nil {
			return nil, errors.NewField("outAmountParam", err)
		}
		// Serialize `quotedInAmountParam`:
		err = enc__.Encode(quotedInAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedInAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
		// Serialize `positiveSlippageBpsParam`:
		err = enc__.Encode(positiveSlippageBpsParam)
		if err != nil {
			return nil, errors.NewField("positiveSlippageBpsParam", err)
		}
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "program_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAuthorityAccount, false, false))
		// Account 1 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 2 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 3 "program_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programSourceTokenAccountAccount, true, false))
		// Account 4 "program_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programDestinationTokenAccountAccount, true, false))
		// Account 5 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 6 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 7 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 8 "source_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 9 "destination_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 10 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 11 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "shared_accounts_route_v2" instruction.
func NewSharedAccountsRouteV2Instruction(
	// Params:
	idParam uint8,
	inAmountParam uint64,
	quotedOutAmountParam uint64,
	slippageBpsParam uint16,
	platformFeeBpsParam uint16,
	positiveSlippageBpsParam uint16,
	routePlanParam []RoutePlanStepV2,

	// Accounts:
	programAuthorityAccount solanago.PublicKey,
	userTransferAuthorityAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	programSourceTokenAccountAccount solanago.PublicKey,
	programDestinationTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SharedAccountsRouteV2[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `idParam`:
		err = enc__.Encode(idParam)
		if err != nil {
			return nil, errors.NewField("idParam", err)
		}
		// Serialize `inAmountParam`:
		err = enc__.Encode(inAmountParam)
		if err != nil {
			return nil, errors.NewField("inAmountParam", err)
		}
		// Serialize `quotedOutAmountParam`:
		err = enc__.Encode(quotedOutAmountParam)
		if err != nil {
			return nil, errors.NewField("quotedOutAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
		// Serialize `platformFeeBpsParam`:
		err = enc__.Encode(platformFeeBpsParam)
		if err != nil {
			return nil, errors.NewField("platformFeeBpsParam", err)
		}
		// Serialize `positiveSlippageBpsParam`:
		err = enc__.Encode(positiveSlippageBpsParam)
		if err != nil {
			return nil, errors.NewField("positiveSlippageBpsParam", err)
		}
		// Serialize `routePlanParam`:
		err = enc__.Encode(routePlanParam)
		if err != nil {
			return nil, errors.NewField("routePlanParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "program_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAuthorityAccount, false, false))
		// Account 1 "user_transfer_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTransferAuthorityAccount, false, true))
		// Account 2 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 3 "program_source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programSourceTokenAccountAccount, true, false))
		// Account 4 "program_destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programDestinationTokenAccountAccount, true, false))
		// Account 5 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 6 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 7 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 8 "source_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 9 "destination_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 10 "event_authority": Read-only, Non-signer, Required, Address: D8cy77BBepLMngZx6ZukaTff5hCt1HrWyKk3Hnd9oitf
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 11 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
