// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package moonshot

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_ConfigAccount:
		value := new(ConfigAccount)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as ConfigAccount: %w", err)
		}
		return value, nil
	case Account_CurveAccount:
		value := new(CurveAccount)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as CurveAccount: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_ConfigAccount(accountData []byte) (*ConfigAccount, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_ConfigAccount {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_ConfigAccount, binary.FormatDiscriminator(discriminator))
	}
	acc := new(ConfigAccount)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type ConfigAccount: %w", err)
	}
	return acc, nil
}

func ParseAccount_CurveAccount(accountData []byte) (*CurveAccount, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_CurveAccount {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_CurveAccount, binary.FormatDiscriminator(discriminator))
	}
	acc := new(CurveAccount)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type CurveAccount: %w", err)
	}
	return acc, nil
}
