// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package moonshot

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "token_mint" instruction.
func NewTokenMintInstruction(
	// Params:
	nameParam string,
	symbolParam string,
	uriParam string,
	decimalsParam uint8,
	collateralCurrencyParam uint8,
	amountParam uint64,
	curveTypeParam uint8,

	// Accounts:
	senderAccount solanago.PublicKey,
	backendAuthorityAccount solanago.PublicKey,
	curveAccountAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	mintMetadataAccount solanago.PublicKey,
	curveTokenAccountAccount solanago.PublicKey,
	configAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	mplTokenMetadataAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_TokenMint[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `nameParam`:
		err = enc__.Encode(nameParam)
		if err != nil {
			return nil, errors.NewField("nameParam", err)
		}
		// Serialize `symbolParam`:
		err = enc__.Encode(symbolParam)
		if err != nil {
			return nil, errors.NewField("symbolParam", err)
		}
		// Serialize `uriParam`:
		err = enc__.Encode(uriParam)
		if err != nil {
			return nil, errors.NewField("uriParam", err)
		}
		// Serialize `decimalsParam`:
		err = enc__.Encode(decimalsParam)
		if err != nil {
			return nil, errors.NewField("decimalsParam", err)
		}
		// Serialize `collateralCurrencyParam`:
		err = enc__.Encode(collateralCurrencyParam)
		if err != nil {
			return nil, errors.NewField("collateralCurrencyParam", err)
		}
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `curveTypeParam`:
		err = enc__.Encode(curveTypeParam)
		if err != nil {
			return nil, errors.NewField("curveTypeParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "sender": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(senderAccount, true, true))
		// Account 1 "backend_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(backendAuthorityAccount, false, true))
		// Account 2 "curve_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(curveAccountAccount, true, false))
		// Account 3 "mint": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, true, true))
		// Account 4 "mint_metadata": Writable, Non-signer, Required
		// Type validating that the account is owned by the System Program = uninitialized
		// seeds should ensure that the address is correct
		accounts__.Append(solanago.NewAccountMeta(mintMetadataAccount, true, false))
		// Account 5 "curve_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(curveTokenAccountAccount, true, false))
		// Account 6 "config_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccountAccount, false, false))
		// Account 7 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 8 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 9 "mpl_token_metadata": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mplTokenMetadataAccount, false, false))
		// Account 10 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "buy" instruction.
func NewBuyInstruction(
	// Params:
	amountParam uint64,
	collateralAmountParam uint64,
	slippageBpsParam uint64,

	// Accounts:
	senderAccount solanago.PublicKey,
	senderTokenAccountAccount solanago.PublicKey,
	curveAccountAccount solanago.PublicKey,
	curveTokenAccountAccount solanago.PublicKey,
	dexFeeAccount solanago.PublicKey,
	helioFeeAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	configAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Buy[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `collateralAmountParam`:
		err = enc__.Encode(collateralAmountParam)
		if err != nil {
			return nil, errors.NewField("collateralAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "sender": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(senderAccount, true, true))
		// Account 1 "sender_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(senderTokenAccountAccount, true, false))
		// Account 2 "curve_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(curveAccountAccount, true, false))
		// Account 3 "curve_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(curveTokenAccountAccount, true, false))
		// Account 4 "dex_fee": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(dexFeeAccount, true, false))
		// Account 5 "helio_fee": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(helioFeeAccount, true, false))
		// Account 6 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 7 "config_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccountAccount, false, false))
		// Account 8 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 9 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 10 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "sell" instruction.
func NewSellInstruction(
	// Params:
	amountParam uint64,
	collateralAmountParam uint64,
	slippageBpsParam uint64,

	// Accounts:
	senderAccount solanago.PublicKey,
	senderTokenAccountAccount solanago.PublicKey,
	curveAccountAccount solanago.PublicKey,
	curveTokenAccountAccount solanago.PublicKey,
	dexFeeAccount solanago.PublicKey,
	helioFeeAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	configAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Sell[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `collateralAmountParam`:
		err = enc__.Encode(collateralAmountParam)
		if err != nil {
			return nil, errors.NewField("collateralAmountParam", err)
		}
		// Serialize `slippageBpsParam`:
		err = enc__.Encode(slippageBpsParam)
		if err != nil {
			return nil, errors.NewField("slippageBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "sender": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(senderAccount, true, true))
		// Account 1 "sender_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(senderTokenAccountAccount, true, false))
		// Account 2 "curve_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(curveAccountAccount, true, false))
		// Account 3 "curve_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(curveTokenAccountAccount, true, false))
		// Account 4 "dex_fee": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(dexFeeAccount, true, false))
		// Account 5 "helio_fee": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(helioFeeAccount, true, false))
		// Account 6 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 7 "config_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccountAccount, false, false))
		// Account 8 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 9 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 10 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "migrate_funds" instruction.
func NewMigrateFundsInstruction(
	backendAuthorityAccount solanago.PublicKey,
	migrationAuthorityAccount solanago.PublicKey,
	curveAccountAccount solanago.PublicKey,
	curveTokenAccountAccount solanago.PublicKey,
	migrationAuthorityTokenAccountAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	configAccountAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "backend_authority": Read-only, Signer, Required
		// BE Authority
		accounts__.Append(solanago.NewAccountMeta(backendAuthorityAccount, false, true))
		// Account 1 "migration_authority": Writable, Signer, Required
		// Migration Authority
		// Owner and Payer over Token Accounts, needs to be mutable
		accounts__.Append(solanago.NewAccountMeta(migrationAuthorityAccount, true, true))
		// Account 2 "curve_account": Writable, Non-signer, Required
		// Curve Account
		// The account is closed after this instruction
		accounts__.Append(solanago.NewAccountMeta(curveAccountAccount, true, false))
		// Account 3 "curve_token_account": Writable, Non-signer, Required
		// Curve Token Account
		// The account is closed after this instruction
		accounts__.Append(solanago.NewAccountMeta(curveTokenAccountAccount, true, false))
		// Account 4 "migration_authority_token_account": Writable, Non-signer, Required
		// Authority token Account
		// Init on demand
		accounts__.Append(solanago.NewAccountMeta(migrationAuthorityTokenAccountAccount, true, false))
		// Account 5 "mint": Writable, Non-signer, Required
		// InterfaceAccount: checks program ownership + deserialize into Mint
		accounts__.Append(solanago.NewAccountMeta(mintAccount, true, false))
		// Account 6 "config_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccountAccount, false, false))
		// Account 7 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 8 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 9 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "config_init" instruction.
func NewConfigInitInstruction(
	// Params:
	migrationAuthorityParam *solanago.PublicKey,
	backendAuthorityParam *solanago.PublicKey,
	configAuthorityParam *solanago.PublicKey,
	helioFeeParam *solanago.PublicKey,
	dexFeeParam *solanago.PublicKey,
	feeBpsParam *uint16,
	dexFeeShareParam *uint8,
	migrationFeeParam *uint64,
	marketcapThresholdParam *uint64,
	marketcapCurrencyParam *uint8,
	minSupportedDecimalPlacesParam *uint8,
	maxSupportedDecimalPlacesParam *uint8,
	minSupportedTokenSupplyParam *uint64,
	maxSupportedTokenSupplyParam *uint64,
	coefBParam *uint32,

	// Accounts:
	configAuthorityAccount solanago.PublicKey,
	configAccountAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ConfigInit[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `migrationAuthorityParam` (optional):
		{
			if migrationAuthorityParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("migrationAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("migrationAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(migrationAuthorityParam)
				if err != nil {
					return nil, errors.NewField("migrationAuthorityParam", err)
				}
			}
		}
		// Serialize `backendAuthorityParam` (optional):
		{
			if backendAuthorityParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("backendAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("backendAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(backendAuthorityParam)
				if err != nil {
					return nil, errors.NewField("backendAuthorityParam", err)
				}
			}
		}
		// Serialize `configAuthorityParam` (optional):
		{
			if configAuthorityParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("configAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("configAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(configAuthorityParam)
				if err != nil {
					return nil, errors.NewField("configAuthorityParam", err)
				}
			}
		}
		// Serialize `helioFeeParam` (optional):
		{
			if helioFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("helioFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("helioFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(helioFeeParam)
				if err != nil {
					return nil, errors.NewField("helioFeeParam", err)
				}
			}
		}
		// Serialize `dexFeeParam` (optional):
		{
			if dexFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("dexFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("dexFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(dexFeeParam)
				if err != nil {
					return nil, errors.NewField("dexFeeParam", err)
				}
			}
		}
		// Serialize `feeBpsParam` (optional):
		{
			if feeBpsParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("feeBpsParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("feeBpsParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(feeBpsParam)
				if err != nil {
					return nil, errors.NewField("feeBpsParam", err)
				}
			}
		}
		// Serialize `dexFeeShareParam` (optional):
		{
			if dexFeeShareParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("dexFeeShareParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("dexFeeShareParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(dexFeeShareParam)
				if err != nil {
					return nil, errors.NewField("dexFeeShareParam", err)
				}
			}
		}
		// Serialize `migrationFeeParam` (optional):
		{
			if migrationFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("migrationFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("migrationFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(migrationFeeParam)
				if err != nil {
					return nil, errors.NewField("migrationFeeParam", err)
				}
			}
		}
		// Serialize `marketcapThresholdParam` (optional):
		{
			if marketcapThresholdParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("marketcapThresholdParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("marketcapThresholdParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(marketcapThresholdParam)
				if err != nil {
					return nil, errors.NewField("marketcapThresholdParam", err)
				}
			}
		}
		// Serialize `marketcapCurrencyParam` (optional):
		{
			if marketcapCurrencyParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("marketcapCurrencyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("marketcapCurrencyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(marketcapCurrencyParam)
				if err != nil {
					return nil, errors.NewField("marketcapCurrencyParam", err)
				}
			}
		}
		// Serialize `minSupportedDecimalPlacesParam` (optional):
		{
			if minSupportedDecimalPlacesParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("minSupportedDecimalPlacesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("minSupportedDecimalPlacesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(minSupportedDecimalPlacesParam)
				if err != nil {
					return nil, errors.NewField("minSupportedDecimalPlacesParam", err)
				}
			}
		}
		// Serialize `maxSupportedDecimalPlacesParam` (optional):
		{
			if maxSupportedDecimalPlacesParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("maxSupportedDecimalPlacesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("maxSupportedDecimalPlacesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(maxSupportedDecimalPlacesParam)
				if err != nil {
					return nil, errors.NewField("maxSupportedDecimalPlacesParam", err)
				}
			}
		}
		// Serialize `minSupportedTokenSupplyParam` (optional):
		{
			if minSupportedTokenSupplyParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("minSupportedTokenSupplyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("minSupportedTokenSupplyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(minSupportedTokenSupplyParam)
				if err != nil {
					return nil, errors.NewField("minSupportedTokenSupplyParam", err)
				}
			}
		}
		// Serialize `maxSupportedTokenSupplyParam` (optional):
		{
			if maxSupportedTokenSupplyParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("maxSupportedTokenSupplyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("maxSupportedTokenSupplyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(maxSupportedTokenSupplyParam)
				if err != nil {
					return nil, errors.NewField("maxSupportedTokenSupplyParam", err)
				}
			}
		}
		// Serialize `coefBParam` (optional):
		{
			if coefBParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("coefBParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("coefBParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(coefBParam)
				if err != nil {
					return nil, errors.NewField("coefBParam", err)
				}
			}
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "config_authority": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAuthorityAccount, true, true))
		// Account 1 "config_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccountAccount, true, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "config_update" instruction.
func NewConfigUpdateInstruction(
	// Params:
	migrationAuthorityParam *solanago.PublicKey,
	backendAuthorityParam *solanago.PublicKey,
	configAuthorityParam *solanago.PublicKey,
	helioFeeParam *solanago.PublicKey,
	dexFeeParam *solanago.PublicKey,
	feeBpsParam *uint16,
	dexFeeShareParam *uint8,
	migrationFeeParam *uint64,
	marketcapThresholdParam *uint64,
	marketcapCurrencyParam *uint8,
	minSupportedDecimalPlacesParam *uint8,
	maxSupportedDecimalPlacesParam *uint8,
	minSupportedTokenSupplyParam *uint64,
	maxSupportedTokenSupplyParam *uint64,
	coefBParam *uint32,

	// Accounts:
	configAuthorityAccount solanago.PublicKey,
	configAccountAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ConfigUpdate[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `migrationAuthorityParam` (optional):
		{
			if migrationAuthorityParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("migrationAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("migrationAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(migrationAuthorityParam)
				if err != nil {
					return nil, errors.NewField("migrationAuthorityParam", err)
				}
			}
		}
		// Serialize `backendAuthorityParam` (optional):
		{
			if backendAuthorityParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("backendAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("backendAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(backendAuthorityParam)
				if err != nil {
					return nil, errors.NewField("backendAuthorityParam", err)
				}
			}
		}
		// Serialize `configAuthorityParam` (optional):
		{
			if configAuthorityParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("configAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("configAuthorityParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(configAuthorityParam)
				if err != nil {
					return nil, errors.NewField("configAuthorityParam", err)
				}
			}
		}
		// Serialize `helioFeeParam` (optional):
		{
			if helioFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("helioFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("helioFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(helioFeeParam)
				if err != nil {
					return nil, errors.NewField("helioFeeParam", err)
				}
			}
		}
		// Serialize `dexFeeParam` (optional):
		{
			if dexFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("dexFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("dexFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(dexFeeParam)
				if err != nil {
					return nil, errors.NewField("dexFeeParam", err)
				}
			}
		}
		// Serialize `feeBpsParam` (optional):
		{
			if feeBpsParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("feeBpsParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("feeBpsParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(feeBpsParam)
				if err != nil {
					return nil, errors.NewField("feeBpsParam", err)
				}
			}
		}
		// Serialize `dexFeeShareParam` (optional):
		{
			if dexFeeShareParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("dexFeeShareParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("dexFeeShareParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(dexFeeShareParam)
				if err != nil {
					return nil, errors.NewField("dexFeeShareParam", err)
				}
			}
		}
		// Serialize `migrationFeeParam` (optional):
		{
			if migrationFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("migrationFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("migrationFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(migrationFeeParam)
				if err != nil {
					return nil, errors.NewField("migrationFeeParam", err)
				}
			}
		}
		// Serialize `marketcapThresholdParam` (optional):
		{
			if marketcapThresholdParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("marketcapThresholdParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("marketcapThresholdParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(marketcapThresholdParam)
				if err != nil {
					return nil, errors.NewField("marketcapThresholdParam", err)
				}
			}
		}
		// Serialize `marketcapCurrencyParam` (optional):
		{
			if marketcapCurrencyParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("marketcapCurrencyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("marketcapCurrencyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(marketcapCurrencyParam)
				if err != nil {
					return nil, errors.NewField("marketcapCurrencyParam", err)
				}
			}
		}
		// Serialize `minSupportedDecimalPlacesParam` (optional):
		{
			if minSupportedDecimalPlacesParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("minSupportedDecimalPlacesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("minSupportedDecimalPlacesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(minSupportedDecimalPlacesParam)
				if err != nil {
					return nil, errors.NewField("minSupportedDecimalPlacesParam", err)
				}
			}
		}
		// Serialize `maxSupportedDecimalPlacesParam` (optional):
		{
			if maxSupportedDecimalPlacesParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("maxSupportedDecimalPlacesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("maxSupportedDecimalPlacesParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(maxSupportedDecimalPlacesParam)
				if err != nil {
					return nil, errors.NewField("maxSupportedDecimalPlacesParam", err)
				}
			}
		}
		// Serialize `minSupportedTokenSupplyParam` (optional):
		{
			if minSupportedTokenSupplyParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("minSupportedTokenSupplyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("minSupportedTokenSupplyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(minSupportedTokenSupplyParam)
				if err != nil {
					return nil, errors.NewField("minSupportedTokenSupplyParam", err)
				}
			}
		}
		// Serialize `maxSupportedTokenSupplyParam` (optional):
		{
			if maxSupportedTokenSupplyParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("maxSupportedTokenSupplyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("maxSupportedTokenSupplyParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(maxSupportedTokenSupplyParam)
				if err != nil {
					return nil, errors.NewField("maxSupportedTokenSupplyParam", err)
				}
			}
		}
		// Serialize `coefBParam` (optional):
		{
			if coefBParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("coefBParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("coefBParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(coefBParam)
				if err != nil {
					return nil, errors.NewField("coefBParam", err)
				}
			}
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "config_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAuthorityAccount, false, true))
		// Account 1 "config_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccountAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
