// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package moonshot

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type Currency binary.BorshEnum

const (
	Currency_Sol Currency = iota
)

func (value Currency) String() string {
	switch value {
	case Currency_Sol:
		return "Sol"
	default:
		return ""
	}
}

type CurveType binary.BorshEnum

const (
	CurveType_LinearV1 CurveType = iota
)

func (value CurveType) String() string {
	switch value {
	case CurveType_LinearV1:
		return "LinearV1"
	default:
		return ""
	}
}

type TradeType binary.BorshEnum

const (
	TradeType_Buy TradeType = iota
	TradeType_Sell
)

func (value TradeType) String() string {
	switch value {
	case TradeType_Buy:
		return "Buy"
	case TradeType_Sell:
		return "Sell"
	default:
		return ""
	}
}

type ConfigAccount struct {
	MigrationAuthority        solanago.PublicKey `json:"migrationAuthority"`
	BackendAuthority          solanago.PublicKey `json:"backendAuthority"`
	ConfigAuthority           solanago.PublicKey `json:"configAuthority"`
	HelioFee                  solanago.PublicKey `json:"helioFee"`
	DexFee                    solanago.PublicKey `json:"dexFee"`
	FeeBps                    uint16             `json:"feeBps"`
	DexFeeShare               uint8              `json:"dexFeeShare"`
	MigrationFee              uint64             `json:"migrationFee"`
	MarketcapThreshold        uint64             `json:"marketcapThreshold"`
	MarketcapCurrency         Currency           `json:"marketcapCurrency"`
	MinSupportedDecimalPlaces uint8              `json:"minSupportedDecimalPlaces"`
	MaxSupportedDecimalPlaces uint8              `json:"maxSupportedDecimalPlaces"`
	MinSupportedTokenSupply   uint64             `json:"minSupportedTokenSupply"`
	MaxSupportedTokenSupply   uint64             `json:"maxSupportedTokenSupply"`
	Bump                      uint8              `json:"bump"`
	CoefB                     uint32             `json:"coefB"`
}

func (obj ConfigAccount) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MigrationAuthority`:
	err = encoder.Encode(obj.MigrationAuthority)
	if err != nil {
		return errors.NewField("MigrationAuthority", err)
	}
	// Serialize `BackendAuthority`:
	err = encoder.Encode(obj.BackendAuthority)
	if err != nil {
		return errors.NewField("BackendAuthority", err)
	}
	// Serialize `ConfigAuthority`:
	err = encoder.Encode(obj.ConfigAuthority)
	if err != nil {
		return errors.NewField("ConfigAuthority", err)
	}
	// Serialize `HelioFee`:
	err = encoder.Encode(obj.HelioFee)
	if err != nil {
		return errors.NewField("HelioFee", err)
	}
	// Serialize `DexFee`:
	err = encoder.Encode(obj.DexFee)
	if err != nil {
		return errors.NewField("DexFee", err)
	}
	// Serialize `FeeBps`:
	err = encoder.Encode(obj.FeeBps)
	if err != nil {
		return errors.NewField("FeeBps", err)
	}
	// Serialize `DexFeeShare`:
	err = encoder.Encode(obj.DexFeeShare)
	if err != nil {
		return errors.NewField("DexFeeShare", err)
	}
	// Serialize `MigrationFee`:
	err = encoder.Encode(obj.MigrationFee)
	if err != nil {
		return errors.NewField("MigrationFee", err)
	}
	// Serialize `MarketcapThreshold`:
	err = encoder.Encode(obj.MarketcapThreshold)
	if err != nil {
		return errors.NewField("MarketcapThreshold", err)
	}
	// Serialize `MarketcapCurrency`:
	err = encoder.Encode(obj.MarketcapCurrency)
	if err != nil {
		return errors.NewField("MarketcapCurrency", err)
	}
	// Serialize `MinSupportedDecimalPlaces`:
	err = encoder.Encode(obj.MinSupportedDecimalPlaces)
	if err != nil {
		return errors.NewField("MinSupportedDecimalPlaces", err)
	}
	// Serialize `MaxSupportedDecimalPlaces`:
	err = encoder.Encode(obj.MaxSupportedDecimalPlaces)
	if err != nil {
		return errors.NewField("MaxSupportedDecimalPlaces", err)
	}
	// Serialize `MinSupportedTokenSupply`:
	err = encoder.Encode(obj.MinSupportedTokenSupply)
	if err != nil {
		return errors.NewField("MinSupportedTokenSupply", err)
	}
	// Serialize `MaxSupportedTokenSupply`:
	err = encoder.Encode(obj.MaxSupportedTokenSupply)
	if err != nil {
		return errors.NewField("MaxSupportedTokenSupply", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `CoefB`:
	err = encoder.Encode(obj.CoefB)
	if err != nil {
		return errors.NewField("CoefB", err)
	}
	return nil
}

func (obj ConfigAccount) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ConfigAccount: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ConfigAccount) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MigrationAuthority`:
	err = decoder.Decode(&obj.MigrationAuthority)
	if err != nil {
		return errors.NewField("MigrationAuthority", err)
	}
	// Deserialize `BackendAuthority`:
	err = decoder.Decode(&obj.BackendAuthority)
	if err != nil {
		return errors.NewField("BackendAuthority", err)
	}
	// Deserialize `ConfigAuthority`:
	err = decoder.Decode(&obj.ConfigAuthority)
	if err != nil {
		return errors.NewField("ConfigAuthority", err)
	}
	// Deserialize `HelioFee`:
	err = decoder.Decode(&obj.HelioFee)
	if err != nil {
		return errors.NewField("HelioFee", err)
	}
	// Deserialize `DexFee`:
	err = decoder.Decode(&obj.DexFee)
	if err != nil {
		return errors.NewField("DexFee", err)
	}
	// Deserialize `FeeBps`:
	err = decoder.Decode(&obj.FeeBps)
	if err != nil {
		return errors.NewField("FeeBps", err)
	}
	// Deserialize `DexFeeShare`:
	err = decoder.Decode(&obj.DexFeeShare)
	if err != nil {
		return errors.NewField("DexFeeShare", err)
	}
	// Deserialize `MigrationFee`:
	err = decoder.Decode(&obj.MigrationFee)
	if err != nil {
		return errors.NewField("MigrationFee", err)
	}
	// Deserialize `MarketcapThreshold`:
	err = decoder.Decode(&obj.MarketcapThreshold)
	if err != nil {
		return errors.NewField("MarketcapThreshold", err)
	}
	// Deserialize `MarketcapCurrency`:
	err = decoder.Decode(&obj.MarketcapCurrency)
	if err != nil {
		return errors.NewField("MarketcapCurrency", err)
	}
	// Deserialize `MinSupportedDecimalPlaces`:
	err = decoder.Decode(&obj.MinSupportedDecimalPlaces)
	if err != nil {
		return errors.NewField("MinSupportedDecimalPlaces", err)
	}
	// Deserialize `MaxSupportedDecimalPlaces`:
	err = decoder.Decode(&obj.MaxSupportedDecimalPlaces)
	if err != nil {
		return errors.NewField("MaxSupportedDecimalPlaces", err)
	}
	// Deserialize `MinSupportedTokenSupply`:
	err = decoder.Decode(&obj.MinSupportedTokenSupply)
	if err != nil {
		return errors.NewField("MinSupportedTokenSupply", err)
	}
	// Deserialize `MaxSupportedTokenSupply`:
	err = decoder.Decode(&obj.MaxSupportedTokenSupply)
	if err != nil {
		return errors.NewField("MaxSupportedTokenSupply", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `CoefB`:
	err = decoder.Decode(&obj.CoefB)
	if err != nil {
		return errors.NewField("CoefB", err)
	}
	return nil
}

func (obj *ConfigAccount) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ConfigAccount: %w", err)
	}
	return nil
}

func UnmarshalConfigAccount(buf []byte) (*ConfigAccount, error) {
	obj := new(ConfigAccount)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CurveAccount struct {
	TotalSupply        uint64             `json:"totalSupply"`
	CurveAmount        uint64             `json:"curveAmount"`
	Mint               solanago.PublicKey `json:"mint"`
	Decimals           uint8              `json:"decimals"`
	CollateralCurrency Currency           `json:"collateralCurrency"`
	CurveType          CurveType          `json:"curveType"`
	MarketcapThreshold uint64             `json:"marketcapThreshold"`
	MarketcapCurrency  Currency           `json:"marketcapCurrency"`
	MigrationFee       uint64             `json:"migrationFee"`
	CoefB              uint32             `json:"coefB"`
	Bump               uint8              `json:"bump"`
}

func (obj CurveAccount) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `TotalSupply`:
	err = encoder.Encode(obj.TotalSupply)
	if err != nil {
		return errors.NewField("TotalSupply", err)
	}
	// Serialize `CurveAmount`:
	err = encoder.Encode(obj.CurveAmount)
	if err != nil {
		return errors.NewField("CurveAmount", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Decimals`:
	err = encoder.Encode(obj.Decimals)
	if err != nil {
		return errors.NewField("Decimals", err)
	}
	// Serialize `CollateralCurrency`:
	err = encoder.Encode(obj.CollateralCurrency)
	if err != nil {
		return errors.NewField("CollateralCurrency", err)
	}
	// Serialize `CurveType`:
	err = encoder.Encode(obj.CurveType)
	if err != nil {
		return errors.NewField("CurveType", err)
	}
	// Serialize `MarketcapThreshold`:
	err = encoder.Encode(obj.MarketcapThreshold)
	if err != nil {
		return errors.NewField("MarketcapThreshold", err)
	}
	// Serialize `MarketcapCurrency`:
	err = encoder.Encode(obj.MarketcapCurrency)
	if err != nil {
		return errors.NewField("MarketcapCurrency", err)
	}
	// Serialize `MigrationFee`:
	err = encoder.Encode(obj.MigrationFee)
	if err != nil {
		return errors.NewField("MigrationFee", err)
	}
	// Serialize `CoefB`:
	err = encoder.Encode(obj.CoefB)
	if err != nil {
		return errors.NewField("CoefB", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj CurveAccount) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CurveAccount: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CurveAccount) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `TotalSupply`:
	err = decoder.Decode(&obj.TotalSupply)
	if err != nil {
		return errors.NewField("TotalSupply", err)
	}
	// Deserialize `CurveAmount`:
	err = decoder.Decode(&obj.CurveAmount)
	if err != nil {
		return errors.NewField("CurveAmount", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Decimals`:
	err = decoder.Decode(&obj.Decimals)
	if err != nil {
		return errors.NewField("Decimals", err)
	}
	// Deserialize `CollateralCurrency`:
	err = decoder.Decode(&obj.CollateralCurrency)
	if err != nil {
		return errors.NewField("CollateralCurrency", err)
	}
	// Deserialize `CurveType`:
	err = decoder.Decode(&obj.CurveType)
	if err != nil {
		return errors.NewField("CurveType", err)
	}
	// Deserialize `MarketcapThreshold`:
	err = decoder.Decode(&obj.MarketcapThreshold)
	if err != nil {
		return errors.NewField("MarketcapThreshold", err)
	}
	// Deserialize `MarketcapCurrency`:
	err = decoder.Decode(&obj.MarketcapCurrency)
	if err != nil {
		return errors.NewField("MarketcapCurrency", err)
	}
	// Deserialize `MigrationFee`:
	err = decoder.Decode(&obj.MigrationFee)
	if err != nil {
		return errors.NewField("MigrationFee", err)
	}
	// Deserialize `CoefB`:
	err = decoder.Decode(&obj.CoefB)
	if err != nil {
		return errors.NewField("CoefB", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *CurveAccount) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CurveAccount: %w", err)
	}
	return nil
}

func UnmarshalCurveAccount(buf []byte) (*CurveAccount, error) {
	obj := new(CurveAccount)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TradeEvent struct {
	Amount           uint64             `json:"amount"`
	CollateralAmount uint64             `json:"collateralAmount"`
	DexFee           uint64             `json:"dexFee"`
	HelioFee         uint64             `json:"helioFee"`
	Allocation       uint64             `json:"allocation"`
	Curve            solanago.PublicKey `json:"curve"`
	CostToken        solanago.PublicKey `json:"costToken"`
	Sender           solanago.PublicKey `json:"sender"`
	Type             TradeType          `json:"type"`
	Label            string             `json:"label"`
}

func (obj TradeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `CollateralAmount`:
	err = encoder.Encode(obj.CollateralAmount)
	if err != nil {
		return errors.NewField("CollateralAmount", err)
	}
	// Serialize `DexFee`:
	err = encoder.Encode(obj.DexFee)
	if err != nil {
		return errors.NewField("DexFee", err)
	}
	// Serialize `HelioFee`:
	err = encoder.Encode(obj.HelioFee)
	if err != nil {
		return errors.NewField("HelioFee", err)
	}
	// Serialize `Allocation`:
	err = encoder.Encode(obj.Allocation)
	if err != nil {
		return errors.NewField("Allocation", err)
	}
	// Serialize `Curve`:
	err = encoder.Encode(obj.Curve)
	if err != nil {
		return errors.NewField("Curve", err)
	}
	// Serialize `CostToken`:
	err = encoder.Encode(obj.CostToken)
	if err != nil {
		return errors.NewField("CostToken", err)
	}
	// Serialize `Sender`:
	err = encoder.Encode(obj.Sender)
	if err != nil {
		return errors.NewField("Sender", err)
	}
	// Serialize `Type`:
	err = encoder.Encode(obj.Type)
	if err != nil {
		return errors.NewField("Type", err)
	}
	// Serialize `Label`:
	err = encoder.Encode(obj.Label)
	if err != nil {
		return errors.NewField("Label", err)
	}
	return nil
}

func (obj TradeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TradeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TradeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `CollateralAmount`:
	err = decoder.Decode(&obj.CollateralAmount)
	if err != nil {
		return errors.NewField("CollateralAmount", err)
	}
	// Deserialize `DexFee`:
	err = decoder.Decode(&obj.DexFee)
	if err != nil {
		return errors.NewField("DexFee", err)
	}
	// Deserialize `HelioFee`:
	err = decoder.Decode(&obj.HelioFee)
	if err != nil {
		return errors.NewField("HelioFee", err)
	}
	// Deserialize `Allocation`:
	err = decoder.Decode(&obj.Allocation)
	if err != nil {
		return errors.NewField("Allocation", err)
	}
	// Deserialize `Curve`:
	err = decoder.Decode(&obj.Curve)
	if err != nil {
		return errors.NewField("Curve", err)
	}
	// Deserialize `CostToken`:
	err = decoder.Decode(&obj.CostToken)
	if err != nil {
		return errors.NewField("CostToken", err)
	}
	// Deserialize `Sender`:
	err = decoder.Decode(&obj.Sender)
	if err != nil {
		return errors.NewField("Sender", err)
	}
	// Deserialize `Type`:
	err = decoder.Decode(&obj.Type)
	if err != nil {
		return errors.NewField("Type", err)
	}
	// Deserialize `Label`:
	err = decoder.Decode(&obj.Label)
	if err != nil {
		return errors.NewField("Label", err)
	}
	return nil
}

func (obj *TradeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TradeEvent: %w", err)
	}
	return nil
}

func UnmarshalTradeEvent(buf []byte) (*TradeEvent, error) {
	obj := new(TradeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type MigrationEvent struct {
	TokensMigrated     uint64 `json:"tokensMigrated"`
	TokensBurned       uint64 `json:"tokensBurned"`
	CollateralMigrated uint64 `json:"collateralMigrated"`
	Fee                uint64 `json:"fee"`
	Label              string `json:"label"`
}

func (obj MigrationEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `TokensMigrated`:
	err = encoder.Encode(obj.TokensMigrated)
	if err != nil {
		return errors.NewField("TokensMigrated", err)
	}
	// Serialize `TokensBurned`:
	err = encoder.Encode(obj.TokensBurned)
	if err != nil {
		return errors.NewField("TokensBurned", err)
	}
	// Serialize `CollateralMigrated`:
	err = encoder.Encode(obj.CollateralMigrated)
	if err != nil {
		return errors.NewField("CollateralMigrated", err)
	}
	// Serialize `Fee`:
	err = encoder.Encode(obj.Fee)
	if err != nil {
		return errors.NewField("Fee", err)
	}
	// Serialize `Label`:
	err = encoder.Encode(obj.Label)
	if err != nil {
		return errors.NewField("Label", err)
	}
	return nil
}

func (obj MigrationEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding MigrationEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *MigrationEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `TokensMigrated`:
	err = decoder.Decode(&obj.TokensMigrated)
	if err != nil {
		return errors.NewField("TokensMigrated", err)
	}
	// Deserialize `TokensBurned`:
	err = decoder.Decode(&obj.TokensBurned)
	if err != nil {
		return errors.NewField("TokensBurned", err)
	}
	// Deserialize `CollateralMigrated`:
	err = decoder.Decode(&obj.CollateralMigrated)
	if err != nil {
		return errors.NewField("CollateralMigrated", err)
	}
	// Deserialize `Fee`:
	err = decoder.Decode(&obj.Fee)
	if err != nil {
		return errors.NewField("Fee", err)
	}
	// Deserialize `Label`:
	err = decoder.Decode(&obj.Label)
	if err != nil {
		return errors.NewField("Label", err)
	}
	return nil
}

func (obj *MigrationEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling MigrationEvent: %w", err)
	}
	return nil
}

func UnmarshalMigrationEvent(buf []byte) (*MigrationEvent, error) {
	obj := new(MigrationEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
