// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package solfi

// Account discriminators
var ()

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_Swap = [8]byte{248, 198, 158, 145, 225, 117, 135, 200}
)
