// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package solfi

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("SV2EYYJyRz2YhfXwXnhNAevDEui5Q6yrfyo13WtupPF")
