// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains constants.

package okx_router

// Constants defined in the IDL:

var SEED_SA = []byte{111, 107, 120, 95, 115, 97}
