// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package okx_router

// Account discriminators
var (
	Account_TokenLedger = [8]byte{156, 247, 9, 188, 54, 108, 85, 77}
)

// Event discriminators
var (
	Event_SwapCpiEvent2                 = [8]byte{21, 94, 224, 53, 220, 232, 193, 94}
	Event_SwapEvent                     = [8]byte{64, 198, 205, 232, 38, 8, 113, 226}
	Event_SwapTobV2CpiEvent2            = [8]byte{244, 105, 184, 90, 60, 165, 36, 33}
	Event_SwapTocV2CpiEvent2            = [8]byte{102, 16, 181, 62, 201, 71, 212, 41}
	Event_SwapWithFeesCpiEvent2         = [8]byte{12, 134, 38, 93, 167, 151, 42, 69}
	Event_SwapWithFeesCpiEventEnhanced2 = [8]byte{84, 79, 219, 247, 218, 156, 219, 177}
)

// Instruction discriminators
var (
	Instruction_Claim                          = [8]byte{62, 198, 214, 193, 213, 159, 108, 210}
	Instruction_ClaimCashbackPumpfun           = [8]byte{83, 1, 245, 125, 201, 207, 209, 249}
	Instruction_ClaimCashbackPumpswap          = [8]byte{253, 242, 176, 173, 217, 78, 100, 25}
	Instruction_CreateTokenAccount             = [8]byte{147, 241, 123, 100, 244, 132, 174, 118}
	Instruction_CreateTokenAccountWithSeed     = [8]byte{125, 191, 239, 140, 66, 8, 9, 228}
	Instruction_InitTokenLedger                = [8]byte{157, 116, 66, 59, 137, 180, 49, 157}
	Instruction_ProxySwap                      = [8]byte{19, 44, 130, 148, 72, 56, 44, 238}
	Instruction_SetTokenLedger                 = [8]byte{228, 85, 185, 112, 78, 79, 77, 2}
	Instruction_Swap                           = [8]byte{248, 198, 158, 145, 225, 117, 135, 200}
	Instruction_SwapTob                        = [8]byte{170, 41, 85, 177, 132, 80, 31, 53}
	Instruction_SwapTobEnhanced                = [8]byte{190, 156, 169, 176, 149, 154, 161, 108}
	Instruction_SwapTobV2                      = [8]byte{72, 1, 215, 242, 8, 75, 54, 216}
	Instruction_SwapTobWithReceiver            = [8]byte{223, 170, 216, 234, 204, 6, 241, 25}
	Instruction_SwapTobWithReceiverTokenLedger = [8]byte{239, 93, 10, 202, 161, 134, 127, 130}
	Instruction_SwapTobWithTokenLedger         = [8]byte{36, 92, 147, 219, 26, 176, 159, 90}
	Instruction_SwapToc                        = [8]byte{187, 201, 212, 51, 16, 155, 236, 60}
	Instruction_SwapTocV2                      = [8]byte{127, 214, 107, 189, 23, 90, 47, 104}
	Instruction_WrapUnwrap                     = [8]byte{220, 101, 139, 249, 41, 190, 118, 199}
	Instruction_WrapUnwrapWithReceiver         = [8]byte{123, 25, 47, 134, 233, 167, 171, 170}
)
