// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package okx_router

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_SwapCpiEvent2:
		value := new(SwapCpiEvent2)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SwapCpiEvent2: %w", err)
		}
		return value, nil
	case Event_SwapEvent:
		value := new(SwapEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SwapEvent: %w", err)
		}
		return value, nil
	case Event_SwapTobV2CpiEvent2:
		value := new(SwapTobV2CpiEvent2)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SwapTobV2CpiEvent2: %w", err)
		}
		return value, nil
	case Event_SwapTocV2CpiEvent2:
		value := new(SwapTocV2CpiEvent2)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SwapTocV2CpiEvent2: %w", err)
		}
		return value, nil
	case Event_SwapWithFeesCpiEvent2:
		value := new(SwapWithFeesCpiEvent2)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SwapWithFeesCpiEvent2: %w", err)
		}
		return value, nil
	case Event_SwapWithFeesCpiEventEnhanced2:
		value := new(SwapWithFeesCpiEventEnhanced2)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SwapWithFeesCpiEventEnhanced2: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_SwapCpiEvent2(eventData []byte) (*SwapCpiEvent2, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SwapCpiEvent2 {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SwapCpiEvent2, binary.FormatDiscriminator(discriminator))
	}
	event := new(SwapCpiEvent2)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SwapCpiEvent2: %w", err)
	}
	return event, nil
}

func ParseEvent_SwapEvent(eventData []byte) (*SwapEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SwapEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SwapEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SwapEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SwapEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SwapTobV2CpiEvent2(eventData []byte) (*SwapTobV2CpiEvent2, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SwapTobV2CpiEvent2 {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SwapTobV2CpiEvent2, binary.FormatDiscriminator(discriminator))
	}
	event := new(SwapTobV2CpiEvent2)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SwapTobV2CpiEvent2: %w", err)
	}
	return event, nil
}

func ParseEvent_SwapTocV2CpiEvent2(eventData []byte) (*SwapTocV2CpiEvent2, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SwapTocV2CpiEvent2 {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SwapTocV2CpiEvent2, binary.FormatDiscriminator(discriminator))
	}
	event := new(SwapTocV2CpiEvent2)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SwapTocV2CpiEvent2: %w", err)
	}
	return event, nil
}

func ParseEvent_SwapWithFeesCpiEvent2(eventData []byte) (*SwapWithFeesCpiEvent2, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SwapWithFeesCpiEvent2 {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SwapWithFeesCpiEvent2, binary.FormatDiscriminator(discriminator))
	}
	event := new(SwapWithFeesCpiEvent2)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SwapWithFeesCpiEvent2: %w", err)
	}
	return event, nil
}

func ParseEvent_SwapWithFeesCpiEventEnhanced2(eventData []byte) (*SwapWithFeesCpiEventEnhanced2, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SwapWithFeesCpiEventEnhanced2 {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SwapWithFeesCpiEventEnhanced2, binary.FormatDiscriminator(discriminator))
	}
	event := new(SwapWithFeesCpiEventEnhanced2)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SwapWithFeesCpiEventEnhanced2: %w", err)
	}
	return event, nil
}
