// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package okx_router

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "claim" instruction.
func NewClaimInstruction(
	signerAccount solanago.PublicKey,
	receiverAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	tokenMintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Writable, Signer, Required, Address: CjoV5B96reuCfPh2rRK11G1QptG97jZdyZArTn3EN1Mj
		accounts__.Append(solanago.NewAccountMeta(signerAccount, true, true))
		// Account 1 "receiver": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(receiverAccount, true, false))
		// Account 2 "source_token_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 3 "destination_token_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 4 "sa_authority": Writable, Non-signer, Required, Address: ARu4n5mFdZogZAravu7CcizaojWnS6oqka37gdLT5SZn
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 5 "token_mint": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(tokenMintAccount, false, false))
		// Account 6 "token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 7 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 8 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "claim_cashback_pumpfun" instruction.
func NewClaimCashbackPumpfunInstruction(
	signerAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	userVolumeAccumulatorAccount solanago.PublicKey,
	receiverAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	pumpfunProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required, Address: CjoV5B96reuCfPh2rRK11G1QptG97jZdyZArTn3EN1Mj
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "sa_authority": Writable, Non-signer, Required, Address: ARu4n5mFdZogZAravu7CcizaojWnS6oqka37gdLT5SZn
		// PumpFun transfers claimed SOL directly to this account (account[0] in the CPI).
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 2 "user_volume_accumulator": Writable, Non-signer, Required
		// Holds native SOL accumulated as cashback; emptied by PumpFun during claim.
		accounts__.Append(solanago.NewAccountMeta(userVolumeAccumulatorAccount, true, false))
		// Account 3 "receiver": Writable, Non-signer, Required
		// after PumpFun deposits it there.
		accounts__.Append(solanago.NewAccountMeta(receiverAccount, true, false))
		// Account 4 "event_authority": Read-only, Non-signer, Required, Address: Ce6TQqeHC9p8KetsN6JsjHK7UTZk7nasjjnr7XxXp9F1
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 6 "pumpfun_program": Read-only, Non-signer, Required, Address: 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P
		accounts__.Append(solanago.NewAccountMeta(pumpfunProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "claim_cashback_pumpswap" instruction.
func NewClaimCashbackPumpswapInstruction(
	signerAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	userVolumeAccumulatorAccount solanago.PublicKey,
	wsolMintAccount solanago.PublicKey,
	splTokenProgramAccount solanago.PublicKey,
	uvaWsolAtaAccount solanago.PublicKey,
	saWsolAtaAccount solanago.PublicKey,
	receiverWsolAtaAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	pumpswapProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Read-only, Signer, Required, Address: CjoV5B96reuCfPh2rRK11G1QptG97jZdyZArTn3EN1Mj
		accounts__.Append(solanago.NewAccountMeta(signerAccount, false, true))
		// Account 1 "sa_authority": Writable, Non-signer, Required, Address: ARu4n5mFdZogZAravu7CcizaojWnS6oqka37gdLT5SZn
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 2 "user_volume_accumulator": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userVolumeAccumulatorAccount, true, false))
		// Account 3 "wsol_mint": Read-only, Non-signer, Required, Address: So11111111111111111111111111111111111111112
		accounts__.Append(solanago.NewAccountMeta(wsolMintAccount, false, false))
		// Account 4 "spl_token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(splTokenProgramAccount, false, false))
		// Account 5 "uva_wsol_ata": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(uvaWsolAtaAccount, true, false))
		// Account 6 "sa_wsol_ata": Writable, Non-signer, Required
		// PumpSwap requires account[5] to be a token account owned by authority_pda
		// (same owner as user_volume_accumulator). WSOL is deposited here by PumpSwap,
		// then forwarded to receiver_wsol_ata via a second SPL transfer.
		accounts__.Append(solanago.NewAccountMeta(saWsolAtaAccount, true, false))
		// Account 7 "receiver_wsol_ata": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(receiverWsolAtaAccount, true, false))
		// Account 8 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 9 "event_authority": Read-only, Non-signer, Required, Address: GS4CU59F31iL7aR2Q8zVS8DRrcRnXX1yjQ66TqNVQnaR
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 10 "pumpswap_program": Read-only, Non-signer, Required, Address: pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA
		accounts__.Append(solanago.NewAccountMeta(pumpswapProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create_token_account" instruction.
func NewCreateTokenAccountInstruction(
	// Params:
	bumpParam uint8,

	// Accounts:
	payerAccount solanago.PublicKey,
	ownerAccount solanago.PublicKey,
	tokenAccountAccount solanago.PublicKey,
	tokenMintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CreateTokenAccount[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `bumpParam`:
		err = enc__.Encode(bumpParam)
		if err != nil {
			return nil, errors.NewField("bumpParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "owner": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, false))
		// Account 2 "token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenAccountAccount, true, false))
		// Account 3 "token_mint": Read-only, Non-signer, Required, Address: So11111111111111111111111111111111111111112
		accounts__.Append(solanago.NewAccountMeta(tokenMintAccount, false, false))
		// Account 4 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "create_token_account_with_seed" instruction.
func NewCreateTokenAccountWithSeedInstruction(
	// Params:
	bumpParam uint8,
	seedParam uint32,

	// Accounts:
	payerAccount solanago.PublicKey,
	ownerAccount solanago.PublicKey,
	tokenAccountAccount solanago.PublicKey,
	tokenMintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CreateTokenAccountWithSeed[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `bumpParam`:
		err = enc__.Encode(bumpParam)
		if err != nil {
			return nil, errors.NewField("bumpParam", err)
		}
		// Serialize `seedParam`:
		err = enc__.Encode(seedParam)
		if err != nil {
			return nil, errors.NewField("seedParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "owner": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ownerAccount, false, false))
		// Account 2 "token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenAccountAccount, true, false))
		// Account 3 "token_mint": Read-only, Non-signer, Required, Address: So11111111111111111111111111111111111111112
		accounts__.Append(solanago.NewAccountMeta(tokenMintAccount, false, false))
		// Account 4 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "init_token_ledger" instruction.
func NewInitTokenLedgerInstruction(
	// Params:
	indexParam uint8,

	// Accounts:
	payerAccount solanago.PublicKey,
	tokenLedgerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_InitTokenLedger[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `indexParam`:
		err = enc__.Encode(indexParam)
		if err != nil {
			return nil, errors.NewField("indexParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "token_ledger": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenLedgerAccount, true, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "proxy_swap" instruction.
func NewProxySwapInstruction(
	// Params:
	argsParam SwapArgs,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ProxySwap[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "sa_authority": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, false, false))
		// Account 6 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 7 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 8 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 9 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 10 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 11 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 12 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 13 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_token_ledger" instruction.
func NewSetTokenLedgerInstruction(
	tokenLedgerAccount solanago.PublicKey,
	tokenAccountAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "token_ledger": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenLedgerAccount, true, false))
		// Account 1 "token_account": Read-only, Non-signer, Required
		// SPL / Token-2022 token account to snapshot.
		accounts__.Append(solanago.NewAccountMeta(tokenAccountAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "swap" instruction.
func NewSwapInstruction(
	// Params:
	argsParam SwapArgs,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Swap[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, false, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 6 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_tob" instruction.
func NewSwapTobInstruction(
	// Params:
	argsParam SwapArgs,
	commissionInfoParam uint32,
	platformFeeRateParam uint16,
	trimRateParam uint8,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	commissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapTob[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
		// Serialize `commissionInfoParam`:
		err = enc__.Encode(commissionInfoParam)
		if err != nil {
			return nil, errors.NewField("commissionInfoParam", err)
		}
		// Serialize `platformFeeRateParam`:
		err = enc__.Encode(platformFeeRateParam)
		if err != nil {
			return nil, errors.NewField("platformFeeRateParam", err)
		}
		// Serialize `trimRateParam`:
		err = enc__.Encode(trimRateParam)
		if err != nil {
			return nil, errors.NewField("trimRateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "commission_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(commissionAccountAccount, true, false))
		// Account 6 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 7 "sa_authority": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 8 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 9 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 10 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 11 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 12 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 14 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 15 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_tob_enhanced" instruction.
func NewSwapTobEnhancedInstruction(
	// Params:
	argsParam SwapArgs,
	commissionInfoParam uint32,
	platformFeeRateParam uint16,
	trimRateParam uint8,
	chargeRateParam uint16,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	commissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapTobEnhanced[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
		// Serialize `commissionInfoParam`:
		err = enc__.Encode(commissionInfoParam)
		if err != nil {
			return nil, errors.NewField("commissionInfoParam", err)
		}
		// Serialize `platformFeeRateParam`:
		err = enc__.Encode(platformFeeRateParam)
		if err != nil {
			return nil, errors.NewField("platformFeeRateParam", err)
		}
		// Serialize `trimRateParam`:
		err = enc__.Encode(trimRateParam)
		if err != nil {
			return nil, errors.NewField("trimRateParam", err)
		}
		// Serialize `chargeRateParam`:
		err = enc__.Encode(chargeRateParam)
		if err != nil {
			return nil, errors.NewField("chargeRateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "commission_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(commissionAccountAccount, true, false))
		// Account 6 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 7 "sa_authority": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 8 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 9 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 10 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 11 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 12 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 14 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 15 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_tob_v2" instruction.
// Used to support commission distribution between parent and child nodes in TOB business
func NewSwapTobV2Instruction(
	// Params:
	argsParam SwapArgs,
	totalCommissionInfoParam uint32,
	parentCommissionRateParam uint32,
	platformFeeRateParam uint16,
	trimRateParam uint8,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	parentCommissionAccountAccount solanago.PublicKey,
	childCommissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapTobV2[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
		// Serialize `totalCommissionInfoParam`:
		err = enc__.Encode(totalCommissionInfoParam)
		if err != nil {
			return nil, errors.NewField("totalCommissionInfoParam", err)
		}
		// Serialize `parentCommissionRateParam`:
		err = enc__.Encode(parentCommissionRateParam)
		if err != nil {
			return nil, errors.NewField("parentCommissionRateParam", err)
		}
		// Serialize `platformFeeRateParam`:
		err = enc__.Encode(platformFeeRateParam)
		if err != nil {
			return nil, errors.NewField("platformFeeRateParam", err)
		}
		// Serialize `trimRateParam`:
		err = enc__.Encode(trimRateParam)
		if err != nil {
			return nil, errors.NewField("trimRateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "parent_commission_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(parentCommissionAccountAccount, true, false))
		// Account 6 "child_commission_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(childCommissionAccountAccount, true, false))
		// Account 7 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 8 "sa_authority": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 9 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 10 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 11 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 12 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 13 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 14 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 15 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 16 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_tob_with_receiver" instruction.
func NewSwapTobWithReceiverInstruction(
	// Params:
	argsParam SwapArgs,
	commissionInfoParam uint32,
	platformFeeRateParam uint16,
	trimRateParam uint8,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	commissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	solReceiverAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapTobWithReceiver[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
		// Serialize `commissionInfoParam`:
		err = enc__.Encode(commissionInfoParam)
		if err != nil {
			return nil, errors.NewField("commissionInfoParam", err)
		}
		// Serialize `platformFeeRateParam`:
		err = enc__.Encode(platformFeeRateParam)
		if err != nil {
			return nil, errors.NewField("platformFeeRateParam", err)
		}
		// Serialize `trimRateParam`:
		err = enc__.Encode(trimRateParam)
		if err != nil {
			return nil, errors.NewField("trimRateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "commission_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(commissionAccountAccount, true, false))
		// Account 6 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 7 "sa_authority": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 8 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 9 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 10 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 11 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 12 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 14 "sol_receiver": Writable, Non-signer, Optional
		// Optional SOL receiver account
		// - None: normal swap or SOL stays with payer
		// - Some: SOL receiver when converting wSOL -> SOL
		accounts__.Append(solanago.NewAccountMeta(solReceiverAccount, true, false))
		// Account 15 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 16 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_tob_with_receiver_token_ledger" instruction.
func NewSwapTobWithReceiverTokenLedgerInstruction(
	// Params:
	argsParam SwapArgsTokenLedger,
	commissionInfoParam uint32,
	platformFeeRateParam uint16,
	trimRateParam uint8,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	commissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	solReceiverAccount solanago.PublicKey,
	tokenLedgerAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapTobWithReceiverTokenLedger[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
		// Serialize `commissionInfoParam`:
		err = enc__.Encode(commissionInfoParam)
		if err != nil {
			return nil, errors.NewField("commissionInfoParam", err)
		}
		// Serialize `platformFeeRateParam`:
		err = enc__.Encode(platformFeeRateParam)
		if err != nil {
			return nil, errors.NewField("platformFeeRateParam", err)
		}
		// Serialize `trimRateParam`:
		err = enc__.Encode(trimRateParam)
		if err != nil {
			return nil, errors.NewField("trimRateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "commission_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(commissionAccountAccount, true, false))
		// Account 6 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 7 "sa_authority": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 8 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 9 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 10 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 11 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 12 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 14 "sol_receiver": Writable, Non-signer, Optional
		// Optional SOL receiver account
		// - None: normal swap or SOL stays with payer
		// - Some: SOL receiver when converting wSOL -> SOL
		accounts__.Append(solanago.NewAccountMeta(solReceiverAccount, true, false))
		// Account 15 "token_ledger": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenLedgerAccount, false, false))
		// Account 16 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 17 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_tob_with_token_ledger" instruction.
func NewSwapTobWithTokenLedgerInstruction(
	// Params:
	argsParam SwapArgsTokenLedger,
	commissionInfoParam uint32,
	platformFeeRateParam uint16,
	trimRateParam uint8,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	commissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenLedgerAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapTobWithTokenLedger[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
		// Serialize `commissionInfoParam`:
		err = enc__.Encode(commissionInfoParam)
		if err != nil {
			return nil, errors.NewField("commissionInfoParam", err)
		}
		// Serialize `platformFeeRateParam`:
		err = enc__.Encode(platformFeeRateParam)
		if err != nil {
			return nil, errors.NewField("platformFeeRateParam", err)
		}
		// Serialize `trimRateParam`:
		err = enc__.Encode(trimRateParam)
		if err != nil {
			return nil, errors.NewField("trimRateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "commission_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(commissionAccountAccount, true, false))
		// Account 6 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 7 "sa_authority": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 8 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 9 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 10 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 11 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 12 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 14 "token_ledger": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenLedgerAccount, false, false))
		// Account 15 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 16 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_toc" instruction.
func NewSwapTocInstruction(
	// Params:
	argsParam SwapArgs,
	commissionInfoParam uint32,
	platformFeeRateParam uint16,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	commissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapToc[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
		// Serialize `commissionInfoParam`:
		err = enc__.Encode(commissionInfoParam)
		if err != nil {
			return nil, errors.NewField("commissionInfoParam", err)
		}
		// Serialize `platformFeeRateParam`:
		err = enc__.Encode(platformFeeRateParam)
		if err != nil {
			return nil, errors.NewField("platformFeeRateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "commission_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(commissionAccountAccount, true, false))
		// Account 6 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 7 "sa_authority": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 8 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 9 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 10 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 11 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 12 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 14 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 15 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "swap_toc_v2" instruction.
// Used to support commission distribution between parent and child nodes in TOC business
func NewSwapTocV2Instruction(
	// Params:
	argsParam SwapArgs,
	totalCommissionInfoParam uint32,
	parentCommissionRateParam uint32,
	platformFeeRateParam uint16,

	// Accounts:
	payerAccount solanago.PublicKey,
	sourceTokenAccountAccount solanago.PublicKey,
	destinationTokenAccountAccount solanago.PublicKey,
	sourceMintAccount solanago.PublicKey,
	destinationMintAccount solanago.PublicKey,
	parentCommissionAccountAccount solanago.PublicKey,
	childCommissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	saAuthorityAccount solanago.PublicKey,
	sourceTokenSaAccount solanago.PublicKey,
	destinationTokenSaAccount solanago.PublicKey,
	sourceTokenProgramAccount solanago.PublicKey,
	destinationTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SwapTocV2[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
		// Serialize `totalCommissionInfoParam`:
		err = enc__.Encode(totalCommissionInfoParam)
		if err != nil {
			return nil, errors.NewField("totalCommissionInfoParam", err)
		}
		// Serialize `parentCommissionRateParam`:
		err = enc__.Encode(parentCommissionRateParam)
		if err != nil {
			return nil, errors.NewField("parentCommissionRateParam", err)
		}
		// Serialize `platformFeeRateParam`:
		err = enc__.Encode(platformFeeRateParam)
		if err != nil {
			return nil, errors.NewField("platformFeeRateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "source_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceTokenAccountAccount, true, false))
		// Account 2 "destination_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationTokenAccountAccount, true, false))
		// Account 3 "source_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(sourceMintAccount, false, false))
		// Account 4 "destination_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(destinationMintAccount, false, false))
		// Account 5 "parent_commission_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(parentCommissionAccountAccount, true, false))
		// Account 6 "child_commission_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(childCommissionAccountAccount, true, false))
		// Account 7 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 8 "sa_authority": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(saAuthorityAccount, true, false))
		// Account 9 "source_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenSaAccount, true, false))
		// Account 10 "destination_token_sa": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenSaAccount, true, false))
		// Account 11 "source_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(sourceTokenProgramAccount, false, false))
		// Account 12 "destination_token_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(destinationTokenProgramAccount, false, false))
		// Account 13 "associated_token_program": Read-only, Non-signer, Optional, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 14 "system_program": Read-only, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 15 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 16 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "wrap_unwrap" instruction.
func NewWrapUnwrapInstruction(
	// Params:
	argsParam PlatformFeeWrapUnwrapArgs,

	// Accounts:
	payerAccount solanago.PublicKey,
	payerWsolAccountAccount solanago.PublicKey,
	wsolMintAccount solanago.PublicKey,
	tempWsolAccountAccount solanago.PublicKey,
	commissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	authorityPdaAccount solanago.PublicKey,
	wsolSaAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_WrapUnwrap[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "payer_wsol_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerWsolAccountAccount, true, false))
		// Account 2 "wsol_mint": Read-only, Non-signer, Required, Address: So11111111111111111111111111111111111111112
		accounts__.Append(solanago.NewAccountMeta(wsolMintAccount, false, false))
		// Account 3 "temp_wsol_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(tempWsolAccountAccount, true, false))
		// Account 4 "commission_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(commissionAccountAccount, true, false))
		// Account 5 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 6 "authority_pda": Writable, Non-signer, Optional
		// Used for signing fee transfers from authority_pda (SOL) or wsol_sa (WSOL)
		accounts__.Append(solanago.NewAccountMeta(authorityPdaAccount, true, false))
		// Account 7 "wsol_sa": Writable, Non-signer, Optional
		// This is the authority_pda's associated token account for WSOL
		accounts__.Append(solanago.NewAccountMeta(wsolSaAccount, true, false))
		// Account 8 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 9 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 10 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 11 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "wrap_unwrap_with_receiver" instruction.
// Wrap/Unwrap with optional specified receiver // - Wrap (SOL -> WSOL): receiver is WSOL token account (ATA) // - Unwrap (WSOL -> SOL): receiver is system account (EOA) // Transfer amount: // - From fee: amount_in // - To fee: amount_in - fees
func NewWrapUnwrapWithReceiverInstruction(
	// Params:
	argsParam PlatformFeeWrapUnwrapArgs,

	// Accounts:
	payerAccount solanago.PublicKey,
	payerWsolAccountAccount solanago.PublicKey,
	wsolMintAccount solanago.PublicKey,
	tempWsolAccountAccount solanago.PublicKey,
	commissionAccountAccount solanago.PublicKey,
	platformFeeAccountAccount solanago.PublicKey,
	authorityPdaAccount solanago.PublicKey,
	wsolSaAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	receiverAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_WrapUnwrapWithReceiver[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `argsParam`:
		err = enc__.Encode(argsParam)
		if err != nil {
			return nil, errors.NewField("argsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "payer_wsol_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerWsolAccountAccount, true, false))
		// Account 2 "wsol_mint": Read-only, Non-signer, Required, Address: So11111111111111111111111111111111111111112
		accounts__.Append(solanago.NewAccountMeta(wsolMintAccount, false, false))
		// Account 3 "temp_wsol_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(tempWsolAccountAccount, true, false))
		// Account 4 "commission_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(commissionAccountAccount, true, false))
		// Account 5 "platform_fee_account": Writable, Non-signer, Optional
		accounts__.Append(solanago.NewAccountMeta(platformFeeAccountAccount, true, false))
		// Account 6 "authority_pda": Writable, Non-signer, Optional
		// Used for signing fee transfers from authority_pda (SOL) or wsol_sa (WSOL)
		accounts__.Append(solanago.NewAccountMeta(authorityPdaAccount, true, false))
		// Account 7 "wsol_sa": Writable, Non-signer, Optional
		// This is the authority_pda's associated token account for WSOL
		accounts__.Append(solanago.NewAccountMeta(wsolSaAccount, true, false))
		// Account 8 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 9 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 10 "receiver": Writable, Non-signer, Required
		// - Wrap: WSOL token account (ATA) to receive WSOL
		// - Unwrap: System account (EOA) to receive SOL
		accounts__.Append(solanago.NewAccountMeta(receiverAccount, true, false))
		// Account 11 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 12 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
