// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package alphq

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "swap" instruction.
func NewSwapInstruction(
	// Params:
	aToBParam uint8,
	amountInParam uint64,
	minAmountOutParam uint64,

	// Accounts:
	userAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketStateAccount solanago.PublicKey,
	userTokenAccountAAccount solanago.PublicKey,
	userTokenAccountBAccount solanago.PublicKey,
	vaultTokenAccountAAccount solanago.PublicKey,
	vaultTokenAccountBAccount solanago.PublicKey,
	tokenAAuthorityAccount solanago.PublicKey,
	tokenBAuthorityAccount solanago.PublicKey,
	vendorKeyAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	instructionsSysvarAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Swap[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `aToBParam`:
		err = enc__.Encode(aToBParam)
		if err != nil {
			return nil, errors.NewField("aToBParam", err)
		}
		// Serialize `amountInParam`:
		err = enc__.Encode(amountInParam)
		if err != nil {
			return nil, errors.NewField("amountInParam", err)
		}
		// Serialize `minAmountOutParam`:
		err = enc__.Encode(minAmountOutParam)
		if err != nil {
			return nil, errors.NewField("minAmountOutParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 2 "market_state": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketStateAccount, true, false))
		// Account 3 "user_token_account_a": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAAccount, true, false))
		// Account 4 "user_token_account_b": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountBAccount, true, false))
		// Account 5 "vault_token_account_a": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(vaultTokenAccountAAccount, true, false))
		// Account 6 "vault_token_account_b": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(vaultTokenAccountBAccount, true, false))
		// Account 7 "token_a_authority": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenAAuthorityAccount, true, false))
		// Account 8 "token_b_authority": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenBAuthorityAccount, true, false))
		// Account 9 "vendor_key": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(vendorKeyAccount, true, false))
		// Account 10 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 11 "instructions_sysvar": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(instructionsSysvarAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
