// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package alphq

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("ALPHAQmeA7bjrVuccPsYPiCvsi428SNwte66Srvs4pHA")
